/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.71
 * Generated at: 2021-11-24 16:07:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.face;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import poly.dto.ContestDTO;
import java.util.List;
import static poly.util.CmmUtil.nvl;

public final class facelogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/view/sidebar.jsp", Long.valueOf(1636443453083L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("static poly.util.CmmUtil.nvl");
    _jspx_imports_classes.add("poly.dto.ContestDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Spoilbroth_StudyPlace</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Abril+Fatface&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/open-iconic-bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/animate.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/magnific-popup.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/ionicons.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/bootstrap-datepicker.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/jquery.timepicker.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/flaticon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/icomoon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- profile -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/profile.css\">\r\n");
      out.write("<link href=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css\" rel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("<script src=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- profile -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- data table -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/css/map.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	#loadingImg {\r\n");
      out.write("	 position: absolute;\r\n");
      out.write("	 left: 50%;\r\n");
      out.write("	 top: 40%;\r\n");
      out.write("	 background: #ffffff00;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	video {\r\n");
      out.write("	    width: 80%;\r\n");
      out.write("	    height: 80%;\r\n");
      out.write("	    position: relative;\r\n");
      out.write("	    margin: 0 auto;\r\n");
      out.write("	}\r\n");
      out.write("	.input100{\r\n");
      out.write("		width: 300px;\r\n");
      out.write("	}\r\n");
      out.write("@media (max-width: 600px) {\r\n");
      out.write("	#loadingImg {\r\n");
      out.write("	 position: absolute;\r\n");
      out.write("	 left: 12%;\r\n");
      out.write("	 top: 40%;\r\n");
      out.write("	 background: #ffffff00;\r\n");
      out.write("	 }\r\n");
      out.write("	video {\r\n");
      out.write("	    width: 100%;\r\n");
      out.write("	    height: 100%;\r\n");
      out.write("	    position: relative;\r\n");
      out.write("	    margin: 0 auto;\r\n");
      out.write("	}\r\n");
      out.write("	.input100{\r\n");
      out.write("		width: 245px;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body data-aos-easing=\"slide\" data-aos-duration=\"800\" data-aos-delay=\"0\">\r\n");
      out.write("\r\n");
      out.write("	<!-- 전체 페이지 START-->\r\n");
      out.write("	<div id=\"colorlib-page\">\r\n");
      out.write("		<!-- START 왼쪽 NANI -->\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("\r\n");


	String id = nvl((String)session.getAttribute("user_id"));
	String date = nvl((String)session.getAttribute("join_dt")); 

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<!-- 구글폰트 -->\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Do+Hyeon&family=Nanum+Pen+Script&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<a href=\"#\" class=\"js-colorlib-nav-toggle colorlib-nav-toggle\"><i></i></a>\r\n");
      out.write("		<aside id=\"colorlib-aside\" role=\"complementary\" class=\"js-fullheight\"\r\n");
      out.write("			style=\"height: 812px;\">\r\n");
      out.write("			\r\n");
      out.write("			<nav id=\"colorlib-main-menu\" role=\"navigation\">\r\n");
      out.write("			<a href=\"single.html\" class=\"img img-2\" style=\"background-image: url(/andrea-master/images/image_1.jpg);\"></a>\r\n");
      out.write("			<div class=\"colorlib-active\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li>\r\n");
      out.write("					");
if(date.isEmpty()) { 
      out.write("\r\n");
      out.write("						<a href=\"/user/login.do\" style=\"font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; font-size: 32px;\">가입 하시겠습니까?</a>\r\n");
      out.write("					");
 } else { 
      out.write("\r\n");
      out.write("						<a href=\"#\" style=\"font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; font-size: 24px;\" method=post>첫방문  : ");
      out.print(date );
      out.write("</a>\r\n");
      out.write("					");
} 
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				</li>\r\n");
      out.write("				<li>\r\n");
      out.write("					");
if(id.isEmpty()) { 
      out.write("\r\n");
      out.write("						<a href=\"/user/login.do\" style= \"font-family: 'Nanum Pen Script', cursive; font-size: 20px; padding-left: 70px;\">Sign in</a>\r\n");
      out.write("					");
 } else { 
      out.write("\r\n");
      out.write("						<a href=\"/user/logOut.do\" style=\" font-family: 'Nanum Pen Script', cursive; font-size: 24px; padding-left: 40px;\">");
      out.print(id );
      out.write(" 님 Log out</a>\r\n");
      out.write("					");
} 
      out.write("\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		<hr style=\" width: 90%; height: 1.5px; border: none; background-color: #666666;\"/>\r\n");
      out.write("				<ul class=\"nav2\">\r\n");
      out.write("					<li class=\"colorlib-active\"><a href=\"/spoilbroth/mystudy.do\">Home</a></li>\r\n");
      out.write("					<li class=\"nana0\"><a href=\"/face/faceregister.do\">Face Register</a></li>\r\n");
      out.write("					<li class=\"nana1\"><a href=\"/mbti/mbtimain.do\">MBTI Analysis</a></li>\r\n");
      out.write("					<li class=\"nana2\"><a href=\"/study/match.do\">Study Matching</a></li>\r\n");
      out.write("					<li class=\"nana3\"><a href=\"/study/contest.do\">Study Imformation</a></li>\r\n");
      out.write("					<li class=\"nana4\"><a href=\"/study/studyplace.do\">Study Place</a></li>\r\n");
      out.write("					<li class=\"nana5\"><a href=\"/mypage/setting.do\">Setting</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</nav>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"colorlib-footer\" style=\"padding-bottom: 20px;\">\r\n");
      out.write("				<h1 id=\"colorlib-logo\" class=\"mb-4\">\r\n");
      out.write("					<a href=\"/spoilbroth/main.do\" style=\"background-image: url(/andrea-master/images/bg_1.jpg); font-size: 57px;\">Spoilbroth</a>\r\n");
      out.write("				</h1>\r\n");
      out.write("				<span style=\"font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; font-size: 28px;\">요리사가 너무 많으면 수프를 망친다.</span>\r\n");
      out.write("				<div class=\"mb-4\">\r\n");
      out.write("					<h3>Subscribe for Spoilbroth</h3>\r\n");
      out.write("					<form action=\"#\" class=\"colorlib-subscribe-form\">\r\n");
      out.write("						<div class=\"form-group d-flex\">\r\n");
      out.write("							<div class=\"icon\">\r\n");
      out.write("								<span class=\"icon-paper-plane\"></span>\r\n");
      out.write("							</div>\r\n");
      out.write("							<input type=\"text\" class=\"form-control\"\r\n");
      out.write("								placeholder=\"Enter Email Address\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("		</aside>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"/andrea-master/js/jquery.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("    var url = window.location.pathname;  \r\n");
      out.write("    var activePage = url.substring(url.lastIndexOf('/')+1);\r\n");
      out.write("    console.log(\"activePage: \" + activePage);\r\n");
      out.write("    \r\n");
      out.write("    $('.nav2 li a').each(function(){  \r\n");
      out.write("        var currentPage = this.href.substring(this.href.lastIndexOf('/')+1);\r\n");
      out.write("		console.log(\"currentPage : \"+currentPage)\r\n");
      out.write("		\r\n");
      out.write("        if (activePage == currentPage) {\r\n");
      out.write("        	$(\".nav2\").find(\".colorlib-active\").removeClass(\"colorlib-active\");\r\n");
      out.write("            $(this).parent().addClass('colorlib-active');\r\n");
      out.write("            $(this).addClass('colorlib-active');\r\n");
      out.write("            \r\n");
      out.write("        }else if(activePage == \"faceregister.do\"){\r\n");
      out.write("        	$(\".nav2\").find(\".colorlib-active\").removeClass(\"colorlib-active\");\r\n");
      out.write("        	$('.nana0').addClass('colorlib-active');\r\n");
      out.write("        }else if(activePage == \"mbtianalysis.do\"){\r\n");
      out.write("        	$(\".nav2\").find(\".colorlib-active\").removeClass(\"colorlib-active\");\r\n");
      out.write("        	$('.nana1').addClass('colorlib-active');\r\n");
      out.write("        }else if(activePage == \"match.do\"){\r\n");
      out.write("        	$(\".nav2\").find(\".colorlib-active\").removeClass(\"colorlib-active\");\r\n");
      out.write("        	$('.nana2').addClass('colorlib-active');\r\n");
      out.write("        }else if(activePage == \"contest.do\"){\r\n");
      out.write("        	$(\".nav2\").find(\".colorlib-active\").removeClass(\"colorlib-active\");\r\n");
      out.write("        	$('.nana3').addClass('colorlib-active');\r\n");
      out.write("        }else if(activePage == \"studyplace.do\"){\r\n");
      out.write("        	$(\".nav2\").find(\".colorlib-active\").removeClass(\"colorlib-active\");\r\n");
      out.write("        	$('.nana4').addClass('colorlib-active');\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		<!-- START 상단 NANI -->\r\n");
      out.write("		<div class=\"padding\" style=\"padding-bottom: 90px;\"></div>\r\n");
      out.write("		<div class=\"sidebar-heading\"\r\n");
      out.write("			style=\"text-align: center; position: fixed; top: 0; width: 100%; background-color: #fff; z-index: 5; padding-top: 20px; font-weight: 500; color: black;\">\r\n");
      out.write("			<div class=\"hh\" style=\"font-size: 23px; height: 32px;\">\r\n");
      out.write("				<span>F</span><span>A</span><span>C</span><span>E</span>&nbsp;<span>L</span><span>O</span><span>G</span><span>I</span><span>N</span>\r\n");
      out.write("			</div>\r\n");
      out.write("			<hr\r\n");
      out.write("				style=\"width: 90%; height: 1.5px; border: none; background-color: #666666;\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- END 상단 NANI -->\r\n");
      out.write("		\r\n");
      out.write("		<!-- 메인 페이지 START-->\r\n");
      out.write("		<div id=\"colorlib-main\">\r\n");
      out.write("			<section class=\"ftco-section ftco-no-pt ftco-no-pb\">\r\n");
      out.write("				<div class=\"container\">\r\n");
      out.write("					<!-- 왼쪽 오른쪽 2분할 -->\r\n");
      out.write("					<div class=\"row d-flex\">\r\n");
      out.write("						<!-- 왼쪽 스크립트 -->\r\n");
      out.write("						<div class=\"col-xl-8 px-md-5\" style=\"background-color: #f7fbff;\">\r\n");
      out.write("\r\n");
      out.write("							<!-- My 프로필 메인화면 -->\r\n");
      out.write("							<div class=\"emp-profile\" style=\"\">\r\n");
      out.write("								<label\r\n");
      out.write("									style=\"font-size: 30px; font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; text-align: center;margin: 0 auto;display: block;\">\r\n");
      out.write("									페이스 로그인 </label>\r\n");
      out.write("								<hr style=\"margin-top: 0px; margin-bottom: 8px;\" />\r\n");
      out.write("								<div class=\"\" style=\"font-size: 11px; margin: 0px;\">\r\n");
      out.write("									<p\r\n");
      out.write("										style=\"font-size: 25px; color: royalblue; margin-bottom: 0px; letter-spacing: 1px; font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive;\">\r\n");
      out.write("										아이디를 입력해주세요.</p>\r\n");
      out.write("									\r\n");
      out.write("									<p\r\n");
      out.write("										style=\"font-size: 25px; color: royalblue; margin-bottom: 0px; letter-spacing: 1px; font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive;\">\r\n");
      out.write("										 눈썹이 보이게 카메라를 바라보세요.</p>\r\n");
      out.write("									\r\n");
      out.write("									<p\r\n");
      out.write("										style=\"font-size: 25px; color: lightcoral; margin-bottom: 0px; letter-spacing: 1px; font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive;\">\r\n");
      out.write("										 로그인 하기 버튼을 누르고</p>\r\n");
      out.write("									\r\n");
      out.write("									<p\r\n");
      out.write("										style=\"font-size: 25px; color: royalblue; letter-spacing: 1px; font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive;\">\r\n");
      out.write("										5초를 기다려 주세요.</p>\r\n");
      out.write("									</hr>\r\n");
      out.write("									<!-- 얼굴 등록하기 -->\r\n");
      out.write("									<div class=\"d-flex card p-3\"\r\n");
      out.write("										style=\"width: 100%; height: 400px; margin-bottom: 10px;\">\r\n");
      out.write("										<!-- 웹캠 보여주기 -->\r\n");
      out.write("\r\n");
      out.write("										<video id=\"video\" width=300 height=300 autoplay muted></video>\r\n");
      out.write("										<canvas id=\"canvas\" width=\"640\" height=\"480\"\r\n");
      out.write("											style=\" display:none; width : 300px; height : 300px;\"></canvas>\r\n");
      out.write("										<div id=\"progress\" class=\"progress mt-4\">\r\n");
      out.write("											<div class=\"progress-bar bg-success\" role=\"progressbar\"\r\n");
      out.write("												style=\"width: calc(100/ 12 * 0%)\"></div>\r\n");
      out.write("										</div>\r\n");
      out.write("										\r\n");
      out.write("										<div class=\"wrap-input100 validate-input m-b-20\"\r\n");
      out.write("										data-validate=\"UserId is required\">\r\n");
      out.write("										<span class=\"label-input100\" style=\"font-size: 25px; font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive;\">ID : </span> <input class=\"input100\"\r\n");
      out.write("											type=\"text\" name=\"user_id\" id=\"user_id\" placeholder=\"아이디를 입력해주세요.\" style=\"height: 38px; margin-top: 13px; font-size: 25px; font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive;\">\r\n");
      out.write("										<span class=\"focus-input100\"></span>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									\r\n");
      out.write("									<button id=\"webcamBtn\" class=\"btn btn-sm btn-primary w-100\"\r\n");
      out.write("										style=\"height: 45px; margin-top: 5px; font-size: 17px;\">로그인하기</button>\r\n");
      out.write("									<!-- 끝 -->\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- My 프로필 메인화면 끝-->\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- 오른쪽 스크립트 -->\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</section>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- 메인 페이지 END-->\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- 전체 페이지 END-->\r\n");
      out.write("\r\n");
      out.write("	<!-- loader -->\r\n");
      out.write("	<div id=\"ftco-loader\" class=\"fullscreen\">\r\n");
      out.write("		<svg class=\"circular\" width=\"48px\" height=\"48px\">\r\n");
      out.write("			<circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\"\r\n");
      out.write("				troke-width=\"4\" stroke=\"#eeeeee\"></circle>\r\n");
      out.write("			<circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\"\r\n");
      out.write("				stroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#F96D00\"></circle></svg>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<script src=\"/andrea-master/js/jquery.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<script src=\"/andrea-master/js/bootstrap.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/jquery.stellar.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<script src=\"/andrea-master/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/aos.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/jquery.animateNumber.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/scrollax.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/main.js\"></script>\r\n");
      out.write("	<script src=\"https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	// 로딩 화면\r\n");
      out.write("	function LoadingWithMask(img) {\r\n");
      out.write("		console.log(\"img : \" + img);\r\n");
      out.write("    //화면의 높이와 너비를 구합니다.\r\n");
      out.write("	    var maskHeight = $(document).height();\r\n");
      out.write("	    var maskWidth  = window.document.body.clientWidth;\r\n");
      out.write("	     \r\n");
      out.write("	    //화면에 출력할 마스크를 설정해줍니다.\r\n");
      out.write("	    var mask       =\"<div id='mask' style='position:absolute; z-index:9000; background-color:#000000; display:none; left:0; top:0;'></div>\";\r\n");
      out.write("	    var loadingImg ='';\r\n");
      out.write("	      \r\n");
      out.write("	    loadingImg +=\"<div id='loadingImg'>\";\r\n");
      out.write("	    loadingImg +=\" <img src=\"+img+\" style='position: absolute; display: block; margin: 0px auto;'/>\";\r\n");
      out.write("	    loadingImg +=\"</div>\"; \r\n");
      out.write("	  \r\n");
      out.write("	    //화면에 레이어 추가\r\n");
      out.write("	    $('body')\r\n");
      out.write("	        .append(mask)\r\n");
      out.write("	        .append(loadingImg)\r\n");
      out.write("	        \r\n");
      out.write("	    //마스크의 높이와 너비를 화면 것으로 만들어 전체 화면을 채웁니다.\r\n");
      out.write("	    $('#mask').css({\r\n");
      out.write("	            'width' : maskWidth\r\n");
      out.write("	            ,'height': maskHeight\r\n");
      out.write("	            ,'opacity' :'0.3'\r\n");
      out.write("	    });\r\n");
      out.write("	  \r\n");
      out.write("	    //마스크 표시\r\n");
      out.write("	    $('#mask').show();  \r\n");
      out.write("	  \r\n");
      out.write("	    //로딩중 이미지 표시\r\n");
      out.write("	    $('#loadingImg').show();\r\n");
      out.write("    \r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	// 로딩 제거 함수\r\n");
      out.write("	function closeLoadingWithMask() {\r\n");
      out.write("	    $('#mask, #loadingImg').hide();\r\n");
      out.write("	    $('#mask, #loadingImg').remove(); \r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\r\n");
      out.write("<script src=\"https://html2canvas.hertzen.com/dist/html2canvas.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("	// var canvas = document.getElementById('canvas');\r\n");
      out.write("	// var context = canvas.getContext('2d');\r\n");
      out.write("\r\n");
      out.write("	window.addEventListener(\"load\", function() {\r\n");
      out.write("		console.log('load start');\r\n");
      out.write("		var video = document.getElementById('video');\r\n");
      out.write("		var facebtn = document.getElementById('webcamBtn');\r\n");
      out.write("		var progress = document.getElementById(\"progress\");\r\n");
      out.write("		var progressbar = progress.querySelector(\".progress-bar\");\r\n");
      out.write("		var imglist = [];\r\n");
      out.write("		var target = null;\r\n");
      out.write("		var myImg = null;\r\n");
      out.write("		var userid = document.getElementById(\"user_id\");\r\n");
      out.write("\r\n");
      out.write("		if (navigator.mediaDevices && navigator.mediaDevices.getUserMedia) {\r\n");
      out.write("			navigator.mediaDevices.getUserMedia({\r\n");
      out.write("				video : true\r\n");
      out.write("			}).then(function(stream) {\r\n");
      out.write("				var video = document.getElementById('video');\r\n");
      out.write("				video.srcObject = stream;\r\n");
      out.write("				video.play();\r\n");
      out.write("			});\r\n");
      out.write("		};\r\n");
      out.write("		var canvas = document.getElementById('canvas');\r\n");
      out.write("		var context = canvas.getContext('2d');\r\n");
      out.write("		var video = document.getElementById('video');\r\n");
      out.write("		\r\n");
      out.write("		function sleep(ms) {\r\n");
      out.write("			  const wakeUpTime = Date.now() + ms;\r\n");
      out.write("			  while (Date.now() < wakeUpTime) {}\r\n");
      out.write("			}\r\n");
      out.write("		function loca(loc){\r\n");
      out.write("			location.href = loc;\r\n");
      out.write("		}\r\n");
      out.write("		facebtn.onclick = function() {\r\n");
      out.write("				console.log(userid.value);\r\n");
      out.write("				imglist.push(userid.value);\r\n");
      out.write("			for (var i = 0; i < 20; i++) {\r\n");
      out.write("				// canvas에 이미지그리기\r\n");
      out.write("				sleep(50);\r\n");
      out.write("				context.drawImage(video, 0, 0, 640, 480);\r\n");
      out.write("				console.log(\"facebtn 함수 진입!\");\r\n");
      out.write("				\r\n");
      out.write("				target = $(\"#video\");\r\n");
      out.write("				// if 자리\r\n");
      out.write("				myImg = canvas.toDataURL(\"image/jpeg\");\r\n");
      out.write("				myImg = myImg.replace(\"data:image/jpeg;base64,\", \"\");\r\n");
      out.write("				imglist.push(myImg);\r\n");
      out.write("				\r\n");
      out.write("			}\r\n");
      out.write("			$(\".progress-bar\").attr('style','width : calc(100/12*'+100+'%)'); \r\n");
      out.write("			progressbar.innerHTML = 100+\"%\";\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			var param = { \r\n");
      out.write("					\"imglist\" : imglist\r\n");
      out.write("				    };\r\n");
      out.write("			\r\n");
      out.write("			console.table(param);\r\n");
      out.write("			$('#video').get(0).pause();\r\n");
      out.write("			imglist = [];\r\n");
      out.write("			LoadingWithMask('/andrea-master/images/Plant.gif');\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type : \"POST\",\r\n");
      out.write("				data: JSON.stringify(param),\r\n");
      out.write("				dataType : \"json\",\r\n");
      out.write("				contentType : \"application/json; charset=utf-8\",\r\n");
      out.write("				url : \"/face/faceanalysis.do\",\r\n");
      out.write("				success : function(data) {\r\n");
      out.write("					if (data == 1) {\r\n");
      out.write("						closeLoadingWithMask();\r\n");
      out.write("						swal(\"인증이 완료 되었습니다.!\")\r\n");
      out.write("						.then((value) => {\r\n");
      out.write("							location.href = \"/face/faceloginProc.do?user_id=\"+userid.value;\r\n");
      out.write("						});\r\n");
      out.write("						\r\n");
      out.write("					} else {\r\n");
      out.write("						closeLoadingWithMask();\r\n");
      out.write("						swal(\"인증이 실패 하였습니다.!\")\r\n");
      out.write("						.then((value) => {\r\n");
      out.write("							location.href = \"/user/login.do\";\r\n");
      out.write("						});\r\n");
      out.write("					}\r\n");
      out.write("				},\r\n");
      out.write("				error : function(a, b, c) {\r\n");
      out.write("					swal(\"에러 발생!\");\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		};\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
