/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.71
 * Generated at: 2021-11-24 16:08:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class findPw_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>SignUp</title>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" href=\"/login/images/icons/favicon.ico\" />\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"/login/vendor/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"/login/fonts/font-awesome-4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"/login/fonts/Linearicons-Free-v1.0.0/icon-font.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"/login/vendor/animate/animate.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"/login/vendor/css-hamburgers/hamburgers.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"/login/vendor/animsition/css/animsition.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"/login/vendor/select2/select2.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"/login/vendor/daterangepicker/daterangepicker.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/login/css/util.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/login/css/main.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<style>\r\n");
      out.write(".container-login100:before {\r\n");
      out.write("	content: \"\";\r\n");
      out.write("	background: url(/login/images/desk20.jpg);\r\n");
      out.write("	padding-bottom: 20px;\r\n");
      out.write("	background-size: cover;\r\n");
      out.write("	opacity: 0.8;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 0px;\r\n");
      out.write("	left: 0px;\r\n");
      out.write("	right: 0px;\r\n");
      out.write("	bottom: 0px;\r\n");
      out.write("}\r\n");
      out.write(".sendNumber{\r\n");
      out.write("	padding: 3px 10px 3px 10px; \r\n");
      out.write("	border-radius: 20px; \r\n");
      out.write("	background-color: #289B14; \r\n");
      out.write("	color: white; \r\n");
      out.write("	font-family: 'Nanum Gothic', sans-serif; \r\n");
      out.write("	font-weight: 400; \r\n");
      out.write("	font-size: 12px; \r\n");
      out.write("	display: inline;\r\n");
      out.write("	float: right;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	//체크 버튼에 따라 아이디/비밀번호 기능이 달라진다\r\n");
      out.write("	function search_check(num) {\r\n");
      out.write("		if (num == '1') {\r\n");
      out.write("			document.getElementById(\"searchP\").style.display = \"none\";\r\n");
      out.write("			document.getElementById(\"searchI\").style.display = \"\";\r\n");
      out.write("		} else {\r\n");
      out.write("			document.getElementById(\"searchI\").style.display = \"none\";\r\n");
      out.write("			document.getElementById(\"searchP\").style.display = \"\";\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"limiter\">\r\n");
      out.write("		<div class=\"container-login100 p-b-20\" style=\"padding-bottom: 20px;\">\r\n");
      out.write("			<div class=\"wrap-login100\">\r\n");
      out.write("			<div class=\"login100-form\"\r\n");
      out.write("                 style=\"font-size: 30px; color: darkcyan; display: block; padding:43px 30px; text-align: center; font-family: 'Nanum Gothic', sans-serif; font-weight: 400;\">\r\n");
      out.write("                비밀번호 찾기</div>\r\n");
      out.write("				<!-- <div class=\"login100-form\"\r\n");
      out.write("					style=\"font-size: 30px; color: darkcyan; display: block; padding: 43px 30px; text-align: center;\">\r\n");
      out.write("					아</div> -->\r\n");
      out.write("				");
      out.write("\r\n");
      out.write("				<div class=\"full\">\r\n");
      out.write("					<div class=\"container\">\r\n");
      out.write("						<div class=\"area_inputs wow fadeIn\">\r\n");
      out.write("							<!-- <div style=\"margin-bottom: 10px;\" class=\"custom-control custom-radio custom-control-inline\">\r\n");
      out.write("								<button type=\"button\" class=\"btn btn-outline-warning active\" onclick=\"search_check(1)\" style=\"border-radius: 5px;\">아이디 찾기</button>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"custom-control custom-radio custom-control-inline\">\r\n");
      out.write("							<span style=\"border-radius: 5px;\"></span>\r\n");
      out.write("								<button type=\"button\" class=\"btn btn-outline-warning active\" onclick=\"search_check(2)\" style=\" border-radius: 5px;\">비밀번호 찾기</button>\r\n");
      out.write("							</div> -->\r\n");
      out.write("							<!-- <div data-role=\"tabs\">\r\n");
      out.write("							<div data-role=\"navbar\">\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"#tab1\">아이디 찾기</a></li>\r\n");
      out.write("									<li><a href=\"#tab2\">비밀번호 찾기</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div> -->\r\n");
      out.write("							<form class=\"login100-form validate-form\" method=\"post\" action=\"/user/findPwProc.do\" onsubmit=\"return doRegUserCheck(this)\">\r\n");
      out.write("								<div class=\"wrap-input100 validate-input m-b-20\">\r\n");
      out.write("									<span class=\"label-input100\">ID</span>\r\n");
      out.write("										<input class=\"input100\" type=\"text\" name=\"user_id\" id=\"user_id\" placeholder=\"Enter userId\">\r\n");
      out.write("                    				<span class=\"focus-input100\"></span>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"wrap-input100 validate-input m-b-20\" style=\"margin-bottom: 10px\">\r\n");
      out.write("									<span class=\"label-input100\">Email</span>\r\n");
      out.write("									<input class=\"input100\" type=\"email\" name=\"user_email\"\r\n");
      out.write("											id=\"user_email\" placeholder=\"Enter useremail\" style=\"display: inline;\">\r\n");
      out.write("								</div>\r\n");
      out.write("			\r\n");
      out.write("								<div class=\"container-login100-form-btn\" style=\"display: block; padding-top: 30px;\">\r\n");
      out.write("									<button class=\"login100-form-btn\" style=\"margin: auto;\" onclick=\"location.href='/user/findPwProc.do'\">임시비밀번호받기</button>\r\n");
      out.write("								</div>\r\n");
      out.write("								\r\n");
      out.write("							</form>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
