/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.71
 * Generated at: 2021-11-25 12:11:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import poly.util.CmmUtil;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("poly.util.CmmUtil");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	String email = CmmUtil.nvl((String)request.getAttribute("email"));
	String nickname = CmmUtil.nvl((String)request.getAttribute("nickname"));


      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>SignUp</title>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" href=\"/login/images/icons/favicon.ico\" />\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"/login/vendor/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"/login/fonts/font-awesome-4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"/login/fonts/Linearicons-Free-v1.0.0/icon-font.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"/login/vendor/animate/animate.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"/login/vendor/css-hamburgers/hamburgers.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"/login/vendor/animsition/css/animsition.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"/login/vendor/select2/select2.min.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"/login/vendor/daterangepicker/daterangepicker.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/login/css/util.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/login/css/main.css\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<style>\r\n");
      out.write(".container-login100:before {\r\n");
      out.write("	content: \"\";\r\n");
      out.write("	background: url(/login/images/desk20.jpg);\r\n");
      out.write("	padding-bottom: 20px;\r\n");
      out.write("	background-size: cover;\r\n");
      out.write("	opacity: 0.8;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 0px;\r\n");
      out.write("	left: 0px;\r\n");
      out.write("	right: 0px;\r\n");
      out.write("	bottom: 0px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("	// 회원가입 정보의 유효성 체크하기\r\n");
      out.write("	function doRegUserCheck(f){\r\n");
      out.write("		\r\n");
      out.write("		if(f.user_id.value==\"\"){\r\n");
      out.write("			alert(\"아이디를 입력하세요.\");\r\n");
      out.write("			f.user_id.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(f.user_email.value==\"\"){\r\n");
      out.write("			alert(\"이메일을 입력하세요.\");\r\n");
      out.write("			f.user_email.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(f.user_pwd.value==\"\"){\r\n");
      out.write("			alert(\"비밀번호를 입력하세요.\");\r\n");
      out.write("			f.user_pwd.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(f.user_dept.value==\"\"){\r\n");
      out.write("			alert(\"소속학과를 입력하세요.\");\r\n");
      out.write("			f.user_dept.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(f.user_age.value==\"\"){\r\n");
      out.write("			alert(\"나이를 입력하세요.\");\r\n");
      out.write("			f.user_age.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"limiter\">\r\n");
      out.write("		<div class=\"container-login100 p-b-20\" style=\"padding-bottom: 20px;\">\r\n");
      out.write("			<div class=\"wrap-login100\">\r\n");
      out.write("				<div class=\"login100-form\"\r\n");
      out.write("					style=\"font-size: 30px; color: darkcyan; padding-bottom: 30px;\">\r\n");
      out.write("					Sign Up</div>\r\n");
      out.write("\r\n");
      out.write("				<form class=\"login100-form validate-form\" method=\"post\"\r\n");
      out.write("					action=\"/user/inserUserInfo.do\"\r\n");
      out.write("					onsubmit=\"return doRegUserCheck(this)\"\r\n");
      out.write("					style=\"padding-top: 30px; padding-bottom: 30px;\">\r\n");
      out.write("\r\n");
      out.write("					<div class=\"wrap-input100 validate-input m-b-20\"\r\n");
      out.write("						data-validate=\"UserId is required\">\r\n");
      out.write("						<span class=\"label-input100\">아이디</span> <input class=\"input100\"\r\n");
      out.write("							type=\"text\" name=\"user_id\" id=\"user_id\"\r\n");
      out.write("							placeholder=\"Enter userId\"> <span class=\"focus-input100\"></span>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"msg m-b-15\"></div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"wrap-input100 validate-input m-b-20\"\r\n");
      out.write("						data-validate=\"UserName is required\">\r\n");
      out.write("						<span class=\"label-input100\">이름</span> <input class=\"input100\"\r\n");
      out.write("							type=\"text\" name=\"user_name\" id=\"user_name\"\r\n");
      out.write("							placeholder=\"Enter userName\" value=\"");
      out.print(nickname );
      out.write("\"> <span\r\n");
      out.write("							class=\"focus-input100\"></span>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"wrap-input100 validate-input m-b-20\"\r\n");
      out.write("						data-validate=\"Useremail is required\">\r\n");
      out.write("						<span class=\"label-input100\">이메일</span> <input class=\"input100\"\r\n");
      out.write("							type=\"email\" name=\"user_email\" id=\"user_email\"\r\n");
      out.write("							placeholder=\"Enter useremail\" value=\"");
      out.print(email );
      out.write("\"> <span\r\n");
      out.write("							class=\"focus-input100\"></span>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"wrap-input100 validate-input m-b-18\"\r\n");
      out.write("						data-validate=\"Password is required\">\r\n");
      out.write("						<span class=\"label-input100\">비밀번호</span> <input class=\"input100\"\r\n");
      out.write("							type=\"password\" name=\"user_pwd\" id=\"newPassWord\"\r\n");
      out.write("							placeholder=\"Enter password\"> <span\r\n");
      out.write("							class=\"focus-input100\"></span>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"wrap-input100 validate-input m-b-18\"\r\n");
      out.write("						data-validate=\"Password is required\">\r\n");
      out.write("						<span class=\"label-input100\">비밀번호 확인</span> <input\r\n");
      out.write("							class=\"input100\" type=\"password\" name=\"user_pwd2\"\r\n");
      out.write("							id=\"passWordCheck\" placeholder=\"your Password Check\"> <span\r\n");
      out.write("							class=\"focus-input100\"></span>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"renew m-b-15\"></div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"wrap-input100 m-b-20\"\r\n");
      out.write("						data-validate=\"userdept is required\">\r\n");
      out.write("						<span class=\"label-input100\">관심분야</span> <select\r\n");
      out.write("							class=\"form-control\" style=\"width: 100%\" name=\"user_dept\">\r\n");
      out.write("							<option value=\"IT개발\" selected>IT개발</option>\r\n");
      out.write("							<option value=\"공모전\">공모전</option>\r\n");
      out.write("							<option value=\"어학/회화\">어학/회화</option>\r\n");
      out.write("							<option value=\"봉사활동\">봉사활동</option>\r\n");
      out.write("							<option value=\"취업/면접\">취업/면접</option>\r\n");
      out.write("							<option value=\"스포츠\">스포츠</option>\r\n");
      out.write("							<option value=\"여행\">여행</option>\r\n");
      out.write("						</select>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"wrap-input100 validate-input m-b-18\"\r\n");
      out.write("						data-validate=\"age is required\">\r\n");
      out.write("						<span class=\"label-input100\">나이</span> <input class=\"input100\"\r\n");
      out.write("							name=\"user_age\" id=\"user_age\" type=\"number\" min='18' max='40'\r\n");
      out.write("							step='1'> <span class=\"focus-input100\"></span>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"padding\" style=\"padding-bottom: 50px;\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<div class=\"container-login100-form-btn\" style=\"padding-top: 20px;\">\r\n");
      out.write("						<button type=\"submit\" class=\"login100-form-btn\"\r\n");
      out.write("							style=\"margin: auto; z-index: 5;\">Register</button>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"/login/vendor/jquery/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"/login/vendor/animsition/js/animsition.min.js\"></script>\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"/login/vendor/bootstrap/js/popper.js\"></script>\r\n");
      out.write("	<script src=\"/login/vendor/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"/login/vendor/select2/select2.min.js\"></script>\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"/login/vendor/daterangepicker/moment.min.js\"></script>\r\n");
      out.write("	<script src=\"/login/vendor/daterangepicker/daterangepicker.js\"></script>\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"/login/vendor/countdowntime/countdowntime.js\"></script>\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"/login/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("			swal ( \"간편 회원가입을 진행합니다.\" )   ;\r\n");
      out.write("	    	// alert(\"간편 회원가입을 진행합니다.\");\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	$('#passWordCheck').on('keyup', function(){\r\n");
      out.write("			\r\n");
      out.write("				var pw = document.getElementById(\"newPassWord\").value; //비밀번호\r\n");
      out.write("				var pw2 = document.getElementById(\"passWordCheck\").value; // 확인 비밀번호\r\n");
      out.write("				\r\n");
      out.write("		if (pw != '' && pw2 == '') {\r\n");
      out.write("			null;\r\n");
      out.write("		} else if (pw != \"\" || pw2 != \"\") {\r\n");
      out.write("			if (pw == pw2) {\r\n");
      out.write("				$(\".renew\").text(\"비밀번호가 일치합니다.\");\r\n");
      out.write("				$(\".renew\").css(\"color\", \"#00f\");\r\n");
      out.write("				newPwd = 'Y';\r\n");
      out.write("			} else {\r\n");
      out.write("				$(\".renew\").text(\"비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("				$(\".renew\").css(\"color\", \"#f00\");\r\n");
      out.write("				newPwd = 'N';\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("	})\r\n");
      out.write("	var doCheck = 'N'\r\n");
      out.write("	\r\n");
      out.write("	$('#user_id').on('keyup', function(){\r\n");
      out.write("		var query = {\r\n");
      out.write("			userId : $(\"#user_id\").val()\r\n");
      out.write("		};\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url : \"/user/idCheck.do\",\r\n");
      out.write("			type : \"post\",\r\n");
      out.write("			data : query,\r\n");
      out.write("			success : function(data) {\r\n");
      out.write("				if (data == 1) {\r\n");
      out.write("					$(\".msg\").text(\"사용하고 있는 아이디입니다.\");\r\n");
      out.write("					$(\".msg\").attr(\"style\", \"color:#f00\");\r\n");
      out.write("					doCheck = 'N'\r\n");
      out.write("				} else {\r\n");
      out.write("					$(\".msg\").text(\"사용 가능한 아이디입니다.\");\r\n");
      out.write("					$(\".msg\").attr(\"style\", \"color:#00f\");\r\n");
      out.write("					//$('#userId').attr(\"disabled\", true);\r\n");
      out.write("					doCheck = 'Y'\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		}); // ajax 끝\r\n");
      out.write("	});\r\n");
      out.write("	function check() {\r\n");
      out.write("		if (doCheck == 'N') {\r\n");
      out.write("			alert(\"사용중인 아이디입니다.\")\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
