/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.71
 * Generated at: 2021-11-22 11:45:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.spoilbroth;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import poly.dto.StudyListDTO;
import java.util.List;
import java.util.*;
import static poly.util.CmmUtil.nvl;

public final class mystudy_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/view/sidebar.jsp", Long.valueOf(1636443453083L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("static poly.util.CmmUtil.nvl");
    _jspx_imports_classes.add("poly.dto.StudyListDTO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String user_id = (String) request.getAttribute("user_id");
	String user_email = (String) request.getAttribute("user_email");
	String user_name = (String) request.getAttribute("user_name");
	String user_mbti = (String) request.getAttribute("user_mbti");
	String user_dept = (String) request.getAttribute("user_dept");
	String user_img = (String) request.getAttribute("user_img");
	String studys = (String) request.getAttribute("user_study");
	List<String> iList = (List<String>)request.getAttribute("iList");
	System.out.print("studys : " + studys);
	int study_count = 0;
	String[] user_study = studys.split(",");
	if (studys.equals("")) {
		study_count = user_study.length - 1;
	} else {
		study_count = user_study.length;
	}
	List<StudyListDTO> pList = (List<StudyListDTO>) request.getAttribute("pList");
	if(pList == null){
		pList = new ArrayList<StudyListDTO>();
	}
	int count = pList.size();
	List<String> mbti_scores = (List<String>)request.getAttribute("mbti_scores");
	
	HashMap<String, Integer> wMap = (HashMap<String, Integer>)request.getAttribute("wMap");
	System.out.print("wMap!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! : " + wMap);
	String[] mbti = {"ENFJ", "ENFP", "ENTJ", "ENTP", "ESFJ",
			"ESFP", "ESTJ", "ESTP", "INFJ", "INFP",
			"INTJ", "INTP", "ISFJ", "ISFP", "ISTJ", "ISTP" };
	
	


      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Spoilbroth_StudyGroup</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Abril+Fatface&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"/andrea-master/css/open-iconic-bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/animate.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"/andrea-master/css/owl.theme.default.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/magnific-popup.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/aos.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/ionicons.min.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"/andrea-master/css/bootstrap-datepicker.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/jquery.timepicker.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/flaticon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/icomoon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- profile -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/profile.css\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- profile -->\r\n");
      out.write("\r\n");
      out.write("<!-- owl -->\r\n");
      out.write("<script src=\"/andrea-master/js/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.2.1/owl.carousel.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.2.1/assets/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.2.1/assets/owl.theme.default.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- owl -->\r\n");
      out.write("\r\n");
      out.write("<!-- card -->\r\n");
      out.write("<style>\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body data-aos-easing=\"slide\" data-aos-duration=\"800\" data-aos-delay=\"0\">\r\n");
      out.write("\r\n");
      out.write("	<!-- 전체 페이지 START-->\r\n");
      out.write("	<div id=\"colorlib-page\">\r\n");
      out.write("		<!-- START 왼쪽 NANI -->\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("\r\n");


	String id = nvl((String)session.getAttribute("user_id"));
	String date = nvl((String)session.getAttribute("join_dt")); 

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<!-- 구글폰트 -->\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Do+Hyeon&family=Nanum+Pen+Script&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<a href=\"#\" class=\"js-colorlib-nav-toggle colorlib-nav-toggle\"><i></i></a>\r\n");
      out.write("		<aside id=\"colorlib-aside\" role=\"complementary\" class=\"js-fullheight\"\r\n");
      out.write("			style=\"height: 812px;\">\r\n");
      out.write("			\r\n");
      out.write("			<nav id=\"colorlib-main-menu\" role=\"navigation\">\r\n");
      out.write("			<a href=\"single.html\" class=\"img img-2\" style=\"background-image: url(/andrea-master/images/image_1.jpg);\"></a>\r\n");
      out.write("			<div class=\"colorlib-active\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li>\r\n");
      out.write("					");
if(date.isEmpty()) { 
      out.write("\r\n");
      out.write("						<a href=\"/user/login.do\" style=\"font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; font-size: 32px;\">가입 하시겠습니까?</a>\r\n");
      out.write("					");
 } else { 
      out.write("\r\n");
      out.write("						<a href=\"#\" style=\"font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; font-size: 24px;\" method=post>첫방문  : ");
      out.print(date );
      out.write("</a>\r\n");
      out.write("					");
} 
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				</li>\r\n");
      out.write("				<li>\r\n");
      out.write("					");
if(id.isEmpty()) { 
      out.write("\r\n");
      out.write("						<a href=\"/user/login.do\" style= \"font-family: 'Nanum Pen Script', cursive; font-size: 20px; padding-left: 70px;\">Sign in</a>\r\n");
      out.write("					");
 } else { 
      out.write("\r\n");
      out.write("						<a href=\"/user/logOut.do\" style=\" font-family: 'Nanum Pen Script', cursive; font-size: 24px; padding-left: 40px;\">");
      out.print(id );
      out.write(" 님 Log out</a>\r\n");
      out.write("					");
} 
      out.write("\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		<hr style=\" width: 90%; height: 1.5px; border: none; background-color: #666666;\"/>\r\n");
      out.write("				<ul class=\"nav2\">\r\n");
      out.write("					<li class=\"colorlib-active\"><a href=\"/spoilbroth/mystudy.do\">Home</a></li>\r\n");
      out.write("					<li class=\"nana0\"><a href=\"/face/faceregister.do\">Face Register</a></li>\r\n");
      out.write("					<li class=\"nana1\"><a href=\"/mbti/mbtimain.do\">MBTI Analysis</a></li>\r\n");
      out.write("					<li class=\"nana2\"><a href=\"/study/match.do\">Study Matching</a></li>\r\n");
      out.write("					<li class=\"nana3\"><a href=\"/study/contest.do\">Study Imformation</a></li>\r\n");
      out.write("					<li class=\"nana4\"><a href=\"/study/studyplace.do\">Study Place</a></li>\r\n");
      out.write("					<li class=\"nana5\"><a href=\"/mypage/setting.do\">Setting</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</nav>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"colorlib-footer\" style=\"padding-bottom: 20px;\">\r\n");
      out.write("				<h1 id=\"colorlib-logo\" class=\"mb-4\">\r\n");
      out.write("					<a href=\"/spoilbroth/main.do\" style=\"background-image: url(/andrea-master/images/bg_1.jpg); font-size: 57px;\">Spoilbroth</a>\r\n");
      out.write("				</h1>\r\n");
      out.write("				<span style=\"font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; font-size: 28px;\">요리사가 너무 많으면 수프를 망친다.</span>\r\n");
      out.write("				<div class=\"mb-4\">\r\n");
      out.write("					<h3>Subscribe for Spoilbroth</h3>\r\n");
      out.write("					<form action=\"#\" class=\"colorlib-subscribe-form\">\r\n");
      out.write("						<div class=\"form-group d-flex\">\r\n");
      out.write("							<div class=\"icon\">\r\n");
      out.write("								<span class=\"icon-paper-plane\"></span>\r\n");
      out.write("							</div>\r\n");
      out.write("							<input type=\"text\" class=\"form-control\"\r\n");
      out.write("								placeholder=\"Enter Email Address\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("		</aside>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"/andrea-master/js/jquery.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("    var url = window.location.pathname;  \r\n");
      out.write("    var activePage = url.substring(url.lastIndexOf('/')+1);\r\n");
      out.write("    console.log(\"activePage: \" + activePage);\r\n");
      out.write("    \r\n");
      out.write("    $('.nav2 li a').each(function(){  \r\n");
      out.write("        var currentPage = this.href.substring(this.href.lastIndexOf('/')+1);\r\n");
      out.write("		console.log(\"currentPage : \"+currentPage)\r\n");
      out.write("		\r\n");
      out.write("        if (activePage == currentPage) {\r\n");
      out.write("        	$(\".nav2\").find(\".colorlib-active\").removeClass(\"colorlib-active\");\r\n");
      out.write("            $(this).parent().addClass('colorlib-active');\r\n");
      out.write("            $(this).addClass('colorlib-active');\r\n");
      out.write("            \r\n");
      out.write("        }else if(activePage == \"faceregister.do\"){\r\n");
      out.write("        	$(\".nav2\").find(\".colorlib-active\").removeClass(\"colorlib-active\");\r\n");
      out.write("        	$('.nana0').addClass('colorlib-active');\r\n");
      out.write("        }else if(activePage == \"mbtianalysis.do\"){\r\n");
      out.write("        	$(\".nav2\").find(\".colorlib-active\").removeClass(\"colorlib-active\");\r\n");
      out.write("        	$('.nana1').addClass('colorlib-active');\r\n");
      out.write("        }else if(activePage == \"match.do\"){\r\n");
      out.write("        	$(\".nav2\").find(\".colorlib-active\").removeClass(\"colorlib-active\");\r\n");
      out.write("        	$('.nana2').addClass('colorlib-active');\r\n");
      out.write("        }else if(activePage == \"contest.do\"){\r\n");
      out.write("        	$(\".nav2\").find(\".colorlib-active\").removeClass(\"colorlib-active\");\r\n");
      out.write("        	$('.nana3').addClass('colorlib-active');\r\n");
      out.write("        }else if(activePage == \"studyplace.do\"){\r\n");
      out.write("        	$(\".nav2\").find(\".colorlib-active\").removeClass(\"colorlib-active\");\r\n");
      out.write("        	$('.nana4').addClass('colorlib-active');\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("		<!-- END 왼쪽 NANI -->\r\n");
      out.write("\r\n");
      out.write("		<!-- START 상단 NANI -->\r\n");
      out.write("		<div class=\"padding\" style=\"padding-bottom: 70px;\"></div>\r\n");
      out.write("		<div class=\"sidebar-heading\"\r\n");
      out.write("			style=\"text-align: center; position: fixed; top: 0; width: 100%; height: 70px; background-color: #fff; z-index: 5; padding-top: 20px; font-weight: 500; color: black;\">\r\n");
      out.write("			<div class=\"hh\" style=\"font-size: 23px; height: 32px;\">\r\n");
      out.write("				<span>M</span><span>Y</span><span>&nbsp;</span><span>S</span><span>T</span><span>U</span><span>D</span><span>Y</span>\r\n");
      out.write("			</div>\r\n");
      out.write("			<hr\r\n");
      out.write("				style=\"width: 90%; height: 1.5px; border: none; background-color: #666666;\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- END 상단 NANI -->\r\n");
      out.write("\r\n");
      out.write("		<!-- 메인 페이지 START-->\r\n");
      out.write("		<div id=\"colorlib-main\">\r\n");
      out.write("			<section class=\"ftco-section ftco-no-pt ftco-no-pb\">\r\n");
      out.write("				<div class=\"container\">\r\n");
      out.write("					<!-- 왼쪽 오른쪽 2분할 -->\r\n");
      out.write("					<div class=\"row d-flex\">\r\n");
      out.write("\r\n");
      out.write("						<!-- 왼쪽 스크립트 -->\r\n");
      out.write("						<div class=\"col-xl-8 px-md-5\" style=\"background-color: #f7fbff;\">\r\n");
      out.write("							\r\n");
      out.write("							<!-- 현재 가입된 MBTI 워드클라우드-->\r\n");
      out.write("							<script src=\"https://cdn.anychart.com/releases/v8/js/anychart-base.min.js\"></script> \r\n");
      out.write("							<script src=\"https://cdn.anychart.com/releases/v8/js/anychart-tag-cloud.min.js\"></script>\r\n");
      out.write("							<div class=\"emp-profile\">\r\n");
      out.write("								<div class=\"chart-area\"> \r\n");
      out.write("									<div id=\"container\" style=\"width:100%; height:100%;\">\r\n");
      out.write("									</div> \r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							\r\n");
      out.write("							<!-- My 프로필 메인화면 -->\r\n");
      out.write("							<div class=\"emp-profile\">\r\n");
      out.write("\r\n");
      out.write("								<!-- 사진 프로필 START -->\r\n");
      out.write("								<div class=\"d-flex\">\r\n");
      out.write("									<div class=\"profile-card\">\r\n");
      out.write("										<form id=\"uploadForm\" enctype=\"multipart/form-data\">\r\n");
      out.write("											<div class=\"d-flex align-items-center\">\r\n");
      out.write("												<div class=\"image\">\r\n");
      out.write("													<img id=\"preview-image\" src=\"");
      out.print(user_img );
      out.write("\" class=\"rounded\" width=\"100%\" alt=\"My Image\">\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div id=\"input-image\" class=\"button mt-2 d-flex flex-row align-items-center\">\r\n");
      out.write("												<input type=\"file\" id=\"file\" name=\"fileUplod\" onchange=\"changeValue(this)\" style=\"display:none\"/>\r\n");
      out.write("												<button class=\"btn btn-sm btn-primary w-100\" id=\"btn-upload\" style=\"margin-right: 2px;\">Select File</button>\r\n");
      out.write("												<button id=\"btnUpload\" class=\"btn btn-sm btn-primary w-100\" style=\"margin-left: 2px;\">Register</button>\r\n");
      out.write("											</div>\r\n");
      out.write("										</form>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"profile-card\"\r\n");
      out.write("										style=\"padding-left: 20px; padding-top: 20px;\">\r\n");
      out.write("										<h5\r\n");
      out.write("											style=\"font-size: 30px; font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; letter-spacing: 13px;\">\r\n");
      out.write("											");
      out.print(user_name);
      out.write("</h5>\r\n");
      out.write("										<h6\r\n");
      out.write("											style=\"font-size: 25px; font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive;\">\r\n");
      out.write("											");
      out.print(user_dept);
      out.write("</h6>\r\n");
      out.write("										<p class=\"mb-2\"\r\n");
      out.write("											style=\"font-size: 20px; font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; color: #6c757d;\">\r\n");
      out.write("											Join Study : <span>");
      out.print(study_count);
      out.write("</span>\r\n");
      out.write("										</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<!-- 사진프로필  END -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("								<hr style=\"margin-top: 10px; margin-bottom: 0px;\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("								<!-- 사용자 정보 START-->\r\n");
      out.write("								<div class=\"row\"\r\n");
      out.write("									style=\"font-size: 18px; font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive;\">\r\n");
      out.write("									<div class=\"col-md-6\">\r\n");
      out.write("										<div class=\"profile-head\">\r\n");
      out.write("											<ul class=\"nav nav-tabs\" id=\"myTab\" role=\"tablist\">\r\n");
      out.write("												<li class=\"nav-item\"><a class=\"nav-link active\"\r\n");
      out.write("													id=\"home-tab\" data-toggle=\"tab\" href=\"#home\" role=\"tab\"\r\n");
      out.write("													aria-controls=\"home\" aria-selected=\"true\">About</a></li>\r\n");
      out.write("												<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("													id=\"profile-tab\" data-toggle=\"tab\" href=\"#profile\"\r\n");
      out.write("													role=\"tab\" aria-controls=\"profile\" aria-selected=\"false\">Timeline</a>\r\n");
      out.write("												</li>\r\n");
      out.write("											</ul>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"row\"\r\n");
      out.write("									style=\"font-size: 18px; font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive;\">\r\n");
      out.write("									<div class=\"col-md-8\">\r\n");
      out.write("										<div class=\"tab-content profile-tab\" id=\"myTabContent\">\r\n");
      out.write("											<div class=\"tab-pane fade show active\" id=\"home\"\r\n");
      out.write("												role=\"tabpanel\" aria-labelledby=\"home-tab\">\r\n");
      out.write("												<div class=\"row\">\r\n");
      out.write("													<div class=\"col-6\">\r\n");
      out.write("														<label>MBTI</label>\r\n");
      out.write("													</div>\r\n");
      out.write("													<div class=\"col-6\">\r\n");
      out.write("														<div style=\"margin-left: 20px; color: #0062cc;\">");
      out.print(user_mbti);
      out.write("</div>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("\r\n");
      out.write("											</div>\r\n");
      out.write("\r\n");
      out.write("											<div class=\"tab-pane fade\" id=\"profile\" role=\"tabpanel\"\r\n");
      out.write("												aria-labelledby=\"profile-tab\">\r\n");
      out.write("												<div class=\"row\">\r\n");
      out.write("													<div class=\"col-md-12\">\r\n");
      out.write("														<label>Join Study Group List</label>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("\r\n");
      out.write("												");

													for (int i = 0; i < study_count; i++) {
												
      out.write("\r\n");
      out.write("												<div class=\"row\">\r\n");
      out.write("													<div style=\"margin-left: 20px; color: #0062cc;\">");
      out.print(user_study[i]);
      out.write("</div>\r\n");
      out.write("												</div>\r\n");
      out.write("												");

													}
												
      out.write("\r\n");
      out.write("\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- 사용자 정보 END-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<!-- Join Study Group -->\r\n");
      out.write("							<!-- 슬라이드 -->\r\n");
      out.write("							\r\n");
      out.write("							<!-- 슬라이드 END-->\r\n");
      out.write("\r\n");
      out.write("							<!-- Join Study Group -->\r\n");
      out.write("							<!-- 그룹목록 START -->\r\n");
      out.write("							<hr style=\"margin-top: 5px; margin-bottom: 0px;\" />\r\n");
      out.write("							<!-- My 프로필 메인화면 -->\r\n");
      out.write("							<label\r\n");
      out.write("								style=\"font-size: 30px; font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; margin-bottom: 0px;\">\r\n");
      out.write("								가입한 스터디 목록 </label>\r\n");
      out.write("							<hr style=\"margin-top: 5px; margin-bottom: 0px;\" />\r\n");
      out.write("\r\n");
      out.write("							<!-- 스터디 목록 정보 START-->\r\n");
      out.write("							");

								int j = 0 ;
								for (StudyListDTO pDTO : pList) {
							
      out.write("\r\n");
      out.write("							");

								String[] arr = pDTO.getStudy_member().split(",");
									int membercount = arr.length;
							
      out.write("\r\n");
      out.write("							<div class=\"emp-profile\">\r\n");
      out.write("								<div class=\"d-flex\">\r\n");
      out.write("									<div class=\"profile-card\">\r\n");
      out.write("										<div class=\"d-flex align-items-center\">\r\n");
      out.write("											<div class=\"image\">\r\n");
      out.write("												<img\r\n");
      out.write("													src=\"");
      out.print(iList.get(j));
      out.write("\"\r\n");
      out.write("													class=\"rounded\" width=\"100%\">\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"button mt-2 d-flex flex-row align-items-center\">\r\n");
      out.write("											\r\n");
      out.write("											<button class=\"btn btn-sm btn-primary w-100\"\r\n");
      out.write("												onclick=\"location.href='/study/studyboard.do?study_name=");
      out.print(pDTO.getStudy_name());
      out.write("'\">\r\n");
      out.write("												Study Join</button>\r\n");
      out.write("											\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"profile-card\"\r\n");
      out.write("										style=\"padding-left: 20px; padding-top: 20px;\">\r\n");
      out.write("										<h5\r\n");
      out.write("											style=\"font-size: 26px; font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; letter-spacing: 8px;\">\r\n");
      out.write("											");
      out.print(pDTO.getStudy_name());
      out.write("</h5>\r\n");
      out.write("										<h6\r\n");
      out.write("											style=\"font-size: 22px; font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive;\">\r\n");
      out.write("											");
      out.print(pDTO.getStudy_title());
      out.write("</h6>\r\n");
      out.write("										<p class=\"mb-2\"\r\n");
      out.write("											style=\"font-size: 20px; font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; color: #6c757d;\">\r\n");
      out.write("											Join Study : <span>");
      out.print(membercount);
      out.write("/5</span>\r\n");
      out.write("										</p>\r\n");
      out.write("										");
      out.write("\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- asd -->\r\n");
      out.write("							<div class=\"emp-profile\">\r\n");
      out.write("								<div class=\"d-flex\">\r\n");
      out.write("									<div class=\"profile-card col-5\" style=\"padding-right:3px; padding-left:3px;\">\r\n");
      out.write("									");
 for(int k=0; k<Integer.parseInt(mbti_scores.get(j)); k++) {
      out.write("\r\n");
      out.write("									<svg version=\"1.1\" id=\"Capa_1\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" x=\"0px\" y=\"0px\" width=\"22\" height=\"22\"\r\n");
      out.write("										 viewBox=\"0 0 422.448 422.448\" style=\"enable-background:new 0 0 422.448 422.448;\" xml:space=\"preserve\">\r\n");
      out.write("									<path style=\"fill:#FF4979;\" d=\"M387.15,59.153c-47.066-47.065-123.374-47.065-170.44,0l-4,4l-4-4\r\n");
      out.write("										C163.342,10.448,87.081,7.742,38.376,53.109s-51.412,121.628-6.044,170.334c1.885,2.023,3.839,3.981,5.858,5.871l170.8,170.8\r\n");
      out.write("										c2.018,1.981,5.217,2.085,7.36,0.24l170.8-170.8c47.065-47.066,47.065-123.374,0-170.44L387.15,59.153z\"/>\r\n");
      out.write("									</svg>\r\n");
      out.write("									\r\n");
      out.write("									");
} 
      out.write("\r\n");
      out.write("									</div>\r\n");
      out.write("									\r\n");
      out.write("									<div class=\"profile-card col-7\">\r\n");
      out.write("										");
 if(Integer.parseInt(mbti_scores.get(j)) >= 0 && Integer.parseInt(mbti_scores.get(j)) <= 2) {
      out.write("\r\n");
      out.write("											<span class=\"mb-2\" style=\"font-size: 18px; font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; color: #ff4500;\">\r\n");
      out.write("											서로 양보하고 노력 해야해요.\r\n");
      out.write("											</span>\r\n");
      out.write("										");
}else if(Integer.parseInt(mbti_scores.get(j)) >= 3 && Integer.parseInt(mbti_scores.get(j)) <= 4 ){
      out.write("\r\n");
      out.write("											<span class=\"mb-2\" style=\"font-size: 18px; font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; color: royalblue;\">\r\n");
      out.write("											이번 기회에 친해져 볼까요?\r\n");
      out.write("											</span>\r\n");
      out.write("										");
}else{
      out.write("\r\n");
      out.write("											<span class=\"mb-2\" style=\"font-size: 18px; font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; color: blueviolet;\">\r\n");
      out.write("											더 없이 좋을수는 없어요. \r\n");
      out.write("											</span>\r\n");
      out.write("										");
} 
      out.write("\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<hr style=\"margin: 5px;\">\r\n");
      out.write("								<p class=\"\" style=\"font-size: 18px; font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; color: red; margin-bottom:0px\">\r\n");
      out.write("								※ 스터디그룹에 가입된 팀원의 MBTI를 분석한 결과입니다.\r\n");
      out.write("								</p>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- asd -->\r\n");
      out.write("							<div class=\"meta-wrap\"\r\n");
      out.write("								style=\"font-size: 22px; font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive;\">\r\n");
      out.write("								<p class=\"meta\">\r\n");
      out.write("									<span style=\"color: cornflowerblue;\"><i\r\n");
      out.write("										class=\"icon-folder-o mr-2\"></i>");
      out.print(pDTO.getStudy_field());
      out.write("</span> <span><i\r\n");
      out.write("										class=\"icon-calendar mr-2\"></i>");
      out.print(pDTO.getStudy_dt());
      out.write("</span>\r\n");
      out.write("								</p>\r\n");
      out.write("								<p class=\"mb-4\" style=\"font-size: 18px;\">");
      out.print(pDTO.getStudy_contents() );
      out.write("</p>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<!-- 스터디 목록 정보 END-->\r\n");
      out.write("							<hr style=\"margin-top: 5px; margin-bottom: 0px;\" />\r\n");
      out.write("							");
 
								j++;							
							} 
      out.write("\r\n");
      out.write("							<!-- 그룹목록 END -->\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</section>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- 메인 페이지 END-->\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- 전체 페이지 END-->\r\n");
      out.write("\r\n");
      out.write("	<!-- loader -->\r\n");
      out.write("	<div id=\"ftco-loader\" class=\"fullscreen\">\r\n");
      out.write("		<svg class=\"circular\" width=\"48px\" height=\"48px\">\r\n");
      out.write("			<circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\"\r\n");
      out.write("				troke-width=\"4\" stroke=\"#eeeeee\"></circle>\r\n");
      out.write("			<circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\"\r\n");
      out.write("				stroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#F96D00\"></circle></svg>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<script src=\"/andrea-master/js/jquery.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/popper.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/bootstrap.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/jquery.stellar.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/owl.carousel.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/aos.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/jquery.animateNumber.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/scrollax.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("		$(function () {\r\n");
      out.write("			$('#btn-upload').click(function (e) {\r\n");
      out.write("				e.preventDefault();\r\n");
      out.write("				$('#file').click();\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		function readImage(input) {\r\n");
      out.write("		    // 인풋 태그에 파일이 있는 경우\r\n");
      out.write("		    if(input.files && input.files[0]) {\r\n");
      out.write("		       \r\n");
      out.write("		        // FileReader 인스턴스 생성\r\n");
      out.write("		        const reader = new FileReader()\r\n");
      out.write("		        // 이미지가 로드가 된 경우\r\n");
      out.write("		        reader.onload = e => {\r\n");
      out.write("		            const previewImage = document.getElementById(\"preview-image\")\r\n");
      out.write("		            console.log(\"previewImage : \" + previewImage)\r\n");
      out.write("		            previewImage.src = e.target.result\r\n");
      out.write("		        }\r\n");
      out.write("		        // reader가 이미지 읽도록 하기\r\n");
      out.write("		        reader.readAsDataURL(input.files[0])\r\n");
      out.write("		    }\r\n");
      out.write("		}\r\n");
      out.write("		// input file에 change 이벤트 부여\r\n");
      out.write("		const inputImage = document.getElementById(\"input-image\")\r\n");
      out.write("		inputImage.addEventListener(\"change\", e => {\r\n");
      out.write("		    readImage(e.target)\r\n");
      out.write("		})\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	$('.slider-1 > .owl-carousel')\r\n");
      out.write("			.owlCarousel(\r\n");
      out.write("					{\r\n");
      out.write("						autoplay : true, // 오토 플레이\r\n");
      out.write("						autoplayTimeout : 3000, // 오토 플레이 시에 다음 슬라이드로 넘어가는 주기, 2초\r\n");
      out.write("						loop : true,\r\n");
      out.write("						margin : 0,\r\n");
      out.write("						nav : true,\r\n");
      out.write("						navText : [],\r\n");
      out.write("						responsive : {\r\n");
      out.write("							0 : {\r\n");
      out.write("								items : 1\r\n");
      out.write("							}\r\n");
      out.write("						}\r\n");
      out.write("					});\r\n");
      out.write("	var $firstDot = $('.slider-1 > .owl-carousel > .owl-dots > .owl-dot.active');\r\n");
      out.write("	$firstDot.removeClass('active');\r\n");
      out.write("	setTimeout(function() {\r\n");
      out.write("		$firstDot.addClass('active');\r\n");
      out.write("	}, 100);\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	$('#btnUpload').on('click', function(event) {\r\n");
      out.write("	    event.preventDefault();\r\n");
      out.write("	    \r\n");
      out.write("	    var form = $('#uploadForm')[0]\r\n");
      out.write("	    var data = new FormData(form);\r\n");
      out.write("	    $('#btnUpload').prop('disabled', true);\r\n");
      out.write("		\r\n");
      out.write("	    $.ajax({\r\n");
      out.write("	        type: \"POST\",\r\n");
      out.write("	        enctype: 'multipart/form-data',\r\n");
      out.write("	        url: \"/FileUplod.do\",\r\n");
      out.write("	        data: data,\r\n");
      out.write("	        processData: false,\r\n");
      out.write("	        contentType: false,\r\n");
      out.write("	        cache: false,\r\n");
      out.write("	        timeout: 600000,\r\n");
      out.write("	        success: function (data) {\r\n");
      out.write("	        	$('#btnUpload').prop('disabled', false);\r\n");
      out.write("	        	swal ('등록이 성공하였습니다.')   ;\r\n");
      out.write("	        },\r\n");
      out.write("	        error: function (e) {\r\n");
      out.write("	            $('#btnUpload').prop('disabled', false);\r\n");
      out.write("	            \r\n");
      out.write("	            swal ('등록이 실패하였습니다.')   ;\r\n");
      out.write("	        }\r\n");
      out.write("	    });\r\n");
      out.write("	})\r\n");
      out.write("</script>\r\n");
      out.write("<script> anychart.onDocumentReady(function () {\r\n");
      out.write("		// forEach\r\n");
      out.write("		// 워드클라우드에 들어가는 key, value\r\n");
      out.write("		var data = [ \r\n");
      out.write("			");
 for(int i=0; i<mbti.length; i++){ 
      out.write("\r\n");
      out.write("				{ \"x\": \"");
      out.print(mbti[i] );
      out.write("\", \"value\": ");
      out.print(wMap.get(mbti[i])+1);
      out.write("*1000000 },\r\n");
      out.write("			");
 } 
      out.write("\r\n");
      out.write("					]; \r\n");
      out.write("		var chart = anychart.tagCloud(data);\r\n");
      out.write("		chart.angles([0]);\r\n");
      out.write("		chart.container(\"container\");\r\n");
      out.write("		chart.draw(); \r\n");
      out.write("	}); \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
