/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.71
 * Generated at: 2021-11-22 12:00:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.study;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import static poly.util.CmmUtil.nvl;

public final class studyopen_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/view/sidebar.jsp", Long.valueOf(1636443453083L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("static poly.util.CmmUtil.nvl");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	String user_id = (String) request.getAttribute("user_id");
	String user_name = (String) request.getAttribute("user_name");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Spoilbroth_StudyGroup</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Abril+Fatface&display=swap\"	rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/open-iconic-bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/animate.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/owl.theme.default.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/magnific-popup.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/aos.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/ionicons.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/bootstrap-datepicker.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/jquery.timepicker.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/flaticon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/icomoon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- profile -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/profile.css\">\r\n");
      out.write("<link href=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css\" rel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("<script src=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- profile -->\r\n");
      out.write("\r\n");
      out.write("<!-- owl -->\r\n");
      out.write("<script src=\"/andrea-master/js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.2.1/owl.carousel.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.2.1/assets/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.2.1/assets/owl.theme.default.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/owlowl.css\">\r\n");
      out.write("<!-- owl -->\r\n");
      out.write("<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	function doRegFileCheck(f){\r\n");
      out.write("		\r\n");
      out.write("		if(f.fileUplod2.value==\"\"){\r\n");
      out.write("			swal ('스터디 이미지를 등록해주세요.');\r\n");
      out.write("			f.fileUplod2.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(f.study_name.value==\"\"){\r\n");
      out.write("			swal ('스터디 이름을 등록해주세요.');\r\n");
      out.write("			f.study_name.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		if(f.study_title.value==\"\"){\r\n");
      out.write("			swal ('스터디 제목을 등록해주세요.');\r\n");
      out.write("			f.study_title.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		if(f.study_contents.value==\"\"){\r\n");
      out.write("			swal ('스터디 메시지를 등록해주세요.');\r\n");
      out.write("			f.study_contents.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body data-aos-easing=\"slide\" data-aos-duration=\"800\" data-aos-delay=\"0\">\r\n");
      out.write("	\r\n");
      out.write("	<!-- 전체 페이지 START-->\r\n");
      out.write("	<div id=\"colorlib-page\">\r\n");
      out.write("		<!-- START 왼쪽 NANI -->\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("\r\n");


	String id = nvl((String)session.getAttribute("user_id"));
	String date = nvl((String)session.getAttribute("join_dt")); 

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<!-- 구글폰트 -->\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Do+Hyeon&family=Nanum+Pen+Script&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<a href=\"#\" class=\"js-colorlib-nav-toggle colorlib-nav-toggle\"><i></i></a>\r\n");
      out.write("		<aside id=\"colorlib-aside\" role=\"complementary\" class=\"js-fullheight\"\r\n");
      out.write("			style=\"height: 812px;\">\r\n");
      out.write("			\r\n");
      out.write("			<nav id=\"colorlib-main-menu\" role=\"navigation\">\r\n");
      out.write("			<a href=\"single.html\" class=\"img img-2\" style=\"background-image: url(/andrea-master/images/image_1.jpg);\"></a>\r\n");
      out.write("			<div class=\"colorlib-active\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li>\r\n");
      out.write("					");
if(date.isEmpty()) { 
      out.write("\r\n");
      out.write("						<a href=\"/user/login.do\" style=\"font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; font-size: 32px;\">가입 하시겠습니까?</a>\r\n");
      out.write("					");
 } else { 
      out.write("\r\n");
      out.write("						<a href=\"#\" style=\"font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; font-size: 24px;\" method=post>첫방문  : ");
      out.print(date );
      out.write("</a>\r\n");
      out.write("					");
} 
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				</li>\r\n");
      out.write("				<li>\r\n");
      out.write("					");
if(id.isEmpty()) { 
      out.write("\r\n");
      out.write("						<a href=\"/user/login.do\" style= \"font-family: 'Nanum Pen Script', cursive; font-size: 20px; padding-left: 70px;\">Sign in</a>\r\n");
      out.write("					");
 } else { 
      out.write("\r\n");
      out.write("						<a href=\"/user/logOut.do\" style=\" font-family: 'Nanum Pen Script', cursive; font-size: 24px; padding-left: 40px;\">");
      out.print(id );
      out.write(" 님 Log out</a>\r\n");
      out.write("					");
} 
      out.write("\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		<hr style=\" width: 90%; height: 1.5px; border: none; background-color: #666666;\"/>\r\n");
      out.write("				<ul class=\"nav2\">\r\n");
      out.write("					<li class=\"colorlib-active\"><a href=\"/spoilbroth/mystudy.do\">Home</a></li>\r\n");
      out.write("					<li class=\"nana0\"><a href=\"/face/faceregister.do\">Face Register</a></li>\r\n");
      out.write("					<li class=\"nana1\"><a href=\"/mbti/mbtimain.do\">MBTI Analysis</a></li>\r\n");
      out.write("					<li class=\"nana2\"><a href=\"/study/match.do\">Study Matching</a></li>\r\n");
      out.write("					<li class=\"nana3\"><a href=\"/study/contest.do\">Study Imformation</a></li>\r\n");
      out.write("					<li class=\"nana4\"><a href=\"/study/studyplace.do\">Study Place</a></li>\r\n");
      out.write("					<li class=\"nana5\"><a href=\"/mypage/setting.do\">Setting</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</nav>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"colorlib-footer\" style=\"padding-bottom: 20px;\">\r\n");
      out.write("				<h1 id=\"colorlib-logo\" class=\"mb-4\">\r\n");
      out.write("					<a href=\"/spoilbroth/main.do\" style=\"background-image: url(/andrea-master/images/bg_1.jpg); font-size: 57px;\">Spoilbroth</a>\r\n");
      out.write("				</h1>\r\n");
      out.write("				<span style=\"font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; font-size: 28px;\">요리사가 너무 많으면 수프를 망친다.</span>\r\n");
      out.write("				<div class=\"mb-4\">\r\n");
      out.write("					<h3>Subscribe for Spoilbroth</h3>\r\n");
      out.write("					<form action=\"#\" class=\"colorlib-subscribe-form\">\r\n");
      out.write("						<div class=\"form-group d-flex\">\r\n");
      out.write("							<div class=\"icon\">\r\n");
      out.write("								<span class=\"icon-paper-plane\"></span>\r\n");
      out.write("							</div>\r\n");
      out.write("							<input type=\"text\" class=\"form-control\"\r\n");
      out.write("								placeholder=\"Enter Email Address\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("		</aside>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"/andrea-master/js/jquery.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("    var url = window.location.pathname;  \r\n");
      out.write("    var activePage = url.substring(url.lastIndexOf('/')+1);\r\n");
      out.write("    console.log(\"activePage: \" + activePage);\r\n");
      out.write("    \r\n");
      out.write("    $('.nav2 li a').each(function(){  \r\n");
      out.write("        var currentPage = this.href.substring(this.href.lastIndexOf('/')+1);\r\n");
      out.write("		console.log(\"currentPage : \"+currentPage)\r\n");
      out.write("		\r\n");
      out.write("        if (activePage == currentPage) {\r\n");
      out.write("        	$(\".nav2\").find(\".colorlib-active\").removeClass(\"colorlib-active\");\r\n");
      out.write("            $(this).parent().addClass('colorlib-active');\r\n");
      out.write("            $(this).addClass('colorlib-active');\r\n");
      out.write("            \r\n");
      out.write("        }else if(activePage == \"faceregister.do\"){\r\n");
      out.write("        	$(\".nav2\").find(\".colorlib-active\").removeClass(\"colorlib-active\");\r\n");
      out.write("        	$('.nana0').addClass('colorlib-active');\r\n");
      out.write("        }else if(activePage == \"mbtianalysis.do\"){\r\n");
      out.write("        	$(\".nav2\").find(\".colorlib-active\").removeClass(\"colorlib-active\");\r\n");
      out.write("        	$('.nana1').addClass('colorlib-active');\r\n");
      out.write("        }else if(activePage == \"match.do\"){\r\n");
      out.write("        	$(\".nav2\").find(\".colorlib-active\").removeClass(\"colorlib-active\");\r\n");
      out.write("        	$('.nana2').addClass('colorlib-active');\r\n");
      out.write("        }else if(activePage == \"contest.do\"){\r\n");
      out.write("        	$(\".nav2\").find(\".colorlib-active\").removeClass(\"colorlib-active\");\r\n");
      out.write("        	$('.nana3').addClass('colorlib-active');\r\n");
      out.write("        }else if(activePage == \"studyplace.do\"){\r\n");
      out.write("        	$(\".nav2\").find(\".colorlib-active\").removeClass(\"colorlib-active\");\r\n");
      out.write("        	$('.nana4').addClass('colorlib-active');\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("		<!-- END 왼쪽 NANI -->\r\n");
      out.write("\r\n");
      out.write("		<!-- START 상단 NANI -->\r\n");
      out.write("		<div class=\"padding\" style=\"padding-bottom: 105px;\"></div>\r\n");
      out.write("		<div class=\"sidebar-heading\" style=\"text-align: center; position: fixed; top: 0; width: 100%; height:130px; background-color: #fff; z-index: 5; padding-top: 20px;font-weight: 500; color: black;\">\r\n");
      out.write("			<div class=\"hh\" style=\"font-size: 23px;height: 32px;\">\r\n");
      out.write("			<span>S</span><span>T</span><span>U</span><span>D</span><span>Y</span><span>&nbsp;</span><span>M</span><span>A</span><span>T</span><span>C</span><span>H</span><span>I</span><span>N</span><span>G</span>\r\n");
      out.write("			</div>\r\n");
      out.write("			<hr style=\" width: 90%; height: 1.5px; border: none; background-color: #666666;\">\r\n");
      out.write("			<ul class=\"tagcloud\" style=\"font-size: 30px; font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive;margin-bottom: 0px;\">\r\n");
      out.write("				<a href=\"/study/match.do\" class=\"tag-cloud-link\" style=\"font-size: 17px; border-width: 1.5px; border-color: #ff0050; float: left; margin-left: 20px;\">이전</a>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- END 상단 NANI -->\r\n");
      out.write("		\r\n");
      out.write("		<!-- 메인 페이지 START-->\r\n");
      out.write("		<div id=\"colorlib-main\">\r\n");
      out.write("			<section class=\"ftco-section ftco-no-pt ftco-no-pb\">\r\n");
      out.write("				<div class=\"container\">\r\n");
      out.write("				\r\n");
      out.write("					<!-- 왼쪽 오른쪽 2분할 -->\r\n");
      out.write("					<div class=\"row d-flex\">\r\n");
      out.write("					\r\n");
      out.write("						<!-- 왼쪽 스크립트 -->\r\n");
      out.write("						<div class=\"col-xl-8 px-md-5\" style=\"background-color: #f7fbff;\">\r\n");
      out.write("							<!-- 스터디 개설  START -->\r\n");
      out.write("							<div class=\"emp-profile\">\r\n");
      out.write("								<label style=\"font-size: 30px; font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive;\">\r\n");
      out.write("								스터디 개설하기\r\n");
      out.write("								</label>\r\n");
      out.write("								<!-- 사진 프로필 START -->\r\n");
      out.write("								<div class=\"d-flex card m-2 p-3\">\r\n");
      out.write("								\r\n");
      out.write("										<form action=\"/study/insertStudyInfo.do\" class=\"p-1 contact-form\" method=\"post\" enctype=\"multipart/form-data\" \r\n");
      out.write("											onsubmit=\"return doRegFileCheck(this)\"\r\n");
      out.write("											style=\"font-size: 30px; font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive;\">\r\n");
      out.write("										<div class=\"profile-card\" style=\"width: 100%;\">\r\n");
      out.write("												<div class=\"align-items-center\">\r\n");
      out.write("													<div class=\"image\">\r\n");
      out.write("														<img id=\"preview-image\" src=\"/img/study.jpg\" class=\"rounded\" width=\"100%\" alt=\"My Image\">\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div id=\"input-image\" class=\"button mt-2 d-flex flex-row align-items-center\">\r\n");
      out.write("													<input type=\"file\" id=\"file\" name=\"fileUplod2\" onchange=\"changeValue(this)\" style=\"display:none;\"/>\r\n");
      out.write("													<button class=\"btn btn-sm btn-primary w-100\" id=\"btn-upload\" style=\"margin-right: 2px;font-size: 20px;\">Select File</button>\r\n");
      out.write("												</div>\r\n");
      out.write("											\r\n");
      out.write("										</div>\r\n");
      out.write("										\r\n");
      out.write("										<div>\r\n");
      out.write("	              							<label style=\"font-size: 22px; font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; margin-bottom: 0px;\">\r\n");
      out.write("											스터디 분야\r\n");
      out.write("											</label>\r\n");
      out.write("	              							<div class=\"form-group\">\r\n");
      out.write("		              							<select class=\"form-control\" style=\"width: 100%; font-size: 22px;\" name=\"study_field\">\r\n");
      out.write("													<option value=\"자유스터디\" selected>자유스터디</option>\r\n");
      out.write("													<option value=\"IT개발\" selected>IT개발</option>\r\n");
      out.write("													<option value=\"공모전\">공모전</option>\r\n");
      out.write("													<option value=\"어학/회화\">어학/회화</option>\r\n");
      out.write("													<option value=\"봉사활동\">봉사활동</option>\r\n");
      out.write("													<option value=\"취업/면접\">취업/면접</option>\r\n");
      out.write("													<option value=\"스포츠\">스포츠</option>\r\n");
      out.write("													<option value=\"여행\">여행</option>\r\n");
      out.write("												</select>\r\n");
      out.write("	              							</div>\r\n");
      out.write("	              							<div class=\"form-group\">\r\n");
      out.write("	                							<input type=\"text\" id=\"study_name\" class=\"form-control\" placeholder=\"Study Name\" name=\"study_name\" style=\"font-size: 20px;\">\r\n");
      out.write("	              							</div>\r\n");
      out.write("	              							<div class=\"form-group\">\r\n");
      out.write("	                							<input type=\"text\" class=\"form-control\" placeholder=\"Study Title\" name=\"study_title\" style=\"font-size: 20px;\">\r\n");
      out.write("	              							</div>\r\n");
      out.write("								            <div class=\"form-group\">\r\n");
      out.write("								                <textarea id=\"\" cols=\"20\" rows=\"7\" class=\"form-control\" placeholder=\"Message\" name=\"study_contents\" style=\"font-size: 18px;\"></textarea>\r\n");
      out.write("								            </div>\r\n");
      out.write("								            <div class=\"form-group text-center\" style=\"font-size:24px;margin-bottom: 0px;\">\r\n");
      out.write("												<input type=\"submit\" value=\"Create Study\" class=\"btn btn-success py-2 px-3\" style=\"font-size: 20px;\">\r\n");
      out.write("								             </div>\r\n");
      out.write("								            <p class=\"mb-3\" style=\"font-size: 20px;font-family: 'Do Hyeon', sans-serif;font-family: 'Nanum Pen Script', cursive;color: #6c757d;float: right;\">\r\n");
      out.write("											By <span>");
      out.print(user_name);
      out.write("</span>\r\n");
      out.write("											</p>\r\n");
      out.write("										</div>\r\n");
      out.write("								        </form>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<!-- 스터디 개설  END -->\r\n");
      out.write("\r\n");
      out.write("								<hr style=\"margin-top: 10px; margin-bottom: 0px;\" />\r\n");
      out.write("								\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- 왼쪽 스크립트 끝 -->\r\n");
      out.write("						\r\n");
      out.write("						<!-- 오른쪽 스크립트 시작 -->\r\n");
      out.write("						\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("			</section>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- 메인 페이지 END-->\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- 전체 페이지 END-->\r\n");
      out.write("\r\n");
      out.write("	<!-- loader -->\r\n");
      out.write("	<div id=\"ftco-loader\" class=\"fullscreen\">\r\n");
      out.write("		<svg class=\"circular\" width=\"48px\" height=\"48px\">\r\n");
      out.write("			<circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" troke-width=\"4\" stroke=\"#eeeeee\"></circle>\r\n");
      out.write("			<circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#F96D00\"></circle></svg>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<script src=\"/andrea-master/js/jquery.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/popper.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/bootstrap.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/jquery.stellar.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/owl.carousel.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/aos.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/jquery.animateNumber.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/scrollax.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("		$(function () {\r\n");
      out.write("			$('#btn-upload').click(function (e) {\r\n");
      out.write("				e.preventDefault();\r\n");
      out.write("				$('#file').click();\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		function readImage(input) {\r\n");
      out.write("		    // 인풋 태그에 파일이 있는 경우\r\n");
      out.write("		    if(input.files && input.files[0]) {\r\n");
      out.write("		       \r\n");
      out.write("		        // FileReader 인스턴스 생성\r\n");
      out.write("		        const reader = new FileReader()\r\n");
      out.write("		        // 이미지가 로드가 된 경우\r\n");
      out.write("		        reader.onload = e => {\r\n");
      out.write("		            const previewImage = document.getElementById(\"preview-image\")\r\n");
      out.write("		            console.log(\"previewImage : \" + previewImage)\r\n");
      out.write("		            previewImage.src = e.target.result\r\n");
      out.write("		        }\r\n");
      out.write("		        // reader가 이미지 읽도록 하기\r\n");
      out.write("		        reader.readAsDataURL(input.files[0])\r\n");
      out.write("		    }\r\n");
      out.write("		}\r\n");
      out.write("		// input file에 change 이벤트 부여\r\n");
      out.write("		const inputImage = document.getElementById(\"input-image\")\r\n");
      out.write("		inputImage.addEventListener(\"change\", e => {\r\n");
      out.write("		    readImage(e.target)\r\n");
      out.write("		})\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
