/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.71
 * Generated at: 2021-11-22 12:00:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.study;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import java.util.List;
import poly.dto.BoardDTO;
import poly.util.CmmUtil;
import poly.dto.StudyListDTO;
import poly.dto.UserDTO;
import static poly.util.CmmUtil.nvl;

public final class studyboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/view/sidebar.jsp", Long.valueOf(1636443453083L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("poly.dto.UserDTO");
    _jspx_imports_classes.add("static poly.util.CmmUtil.nvl");
    _jspx_imports_classes.add("poly.dto.StudyListDTO");
    _jspx_imports_classes.add("poly.util.CmmUtil");
    _jspx_imports_classes.add("poly.dto.BoardDTO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	UserDTO uDTO = (UserDTO) request.getAttribute("rDTO");
String user_id = uDTO.getUser_id();
String user_name = uDTO.getUser_name();

StudyListDTO sDTO = (StudyListDTO) request.getAttribute("sDTO");
String study_name = (String) request.getAttribute("study_name");
String study_notify = CmmUtil.nvl(sDTO.getStudy_notify());
String study_title = CmmUtil.nvl(sDTO.getStudy_title());
String study_creator = CmmUtil.nvl(sDTO.getStudy_creator());
String study_seq = CmmUtil.nvl(sDTO.getStudy_seq());
System.out.println("study_creator : " + study_creator);
System.out.println("study_seq : " + study_seq);

String[] study_group = user_name.split("");
int study_count = study_group.length;

// 게시판 조회 결과 보여주기
List<BoardDTO> rList = (List<BoardDTO>) request.getAttribute("rList");
if (rList == null) {
	rList = new ArrayList<BoardDTO>();
}

// 스터디그룹에 가입한 유저의 MBTI정보
List<String> mList = (List<String>) request.getAttribute("mList");
String member_mbti = String.join(",", mList);

int mbti_score = (int) request.getAttribute("mbti_score");
String study_img = (String) request.getAttribute("study_img");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Spoilbroth_StudyGroup</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Abril+Fatface&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"/andrea-master/css/open-iconic-bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/animate.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"/andrea-master/css/owl.theme.default.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/magnific-popup.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/aos.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/ionicons.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"/andrea-master/css/bootstrap-datepicker.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/jquery.timepicker.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/flaticon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/icomoon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- profile -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/profile.css\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- profile -->\r\n");
      out.write("\r\n");
      out.write("<!-- owl -->\r\n");
      out.write("<script src=\"/andrea-master/js/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.2.1/owl.carousel.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.2.1/assets/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.2.1/assets/owl.theme.default.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/owlowl.css\">\r\n");
      out.write("<!-- data table -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body data-aos-easing=\"slide\" data-aos-duration=\"800\" data-aos-delay=\"0\">\r\n");
      out.write("\r\n");
      out.write("	<!-- 전체 페이지 START-->\r\n");
      out.write("	<div id=\"colorlib-page\">\r\n");
      out.write("		<!-- START 왼쪽 NANI -->\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("\r\n");


	String id = nvl((String)session.getAttribute("user_id"));
	String date = nvl((String)session.getAttribute("join_dt")); 

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<!-- 구글폰트 -->\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Do+Hyeon&family=Nanum+Pen+Script&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<a href=\"#\" class=\"js-colorlib-nav-toggle colorlib-nav-toggle\"><i></i></a>\r\n");
      out.write("		<aside id=\"colorlib-aside\" role=\"complementary\" class=\"js-fullheight\"\r\n");
      out.write("			style=\"height: 812px;\">\r\n");
      out.write("			\r\n");
      out.write("			<nav id=\"colorlib-main-menu\" role=\"navigation\">\r\n");
      out.write("			<a href=\"single.html\" class=\"img img-2\" style=\"background-image: url(/andrea-master/images/image_1.jpg);\"></a>\r\n");
      out.write("			<div class=\"colorlib-active\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li>\r\n");
      out.write("					");
if(date.isEmpty()) { 
      out.write("\r\n");
      out.write("						<a href=\"/user/login.do\" style=\"font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; font-size: 32px;\">가입 하시겠습니까?</a>\r\n");
      out.write("					");
 } else { 
      out.write("\r\n");
      out.write("						<a href=\"#\" style=\"font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; font-size: 24px;\" method=post>첫방문  : ");
      out.print(date );
      out.write("</a>\r\n");
      out.write("					");
} 
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				</li>\r\n");
      out.write("				<li>\r\n");
      out.write("					");
if(id.isEmpty()) { 
      out.write("\r\n");
      out.write("						<a href=\"/user/login.do\" style= \"font-family: 'Nanum Pen Script', cursive; font-size: 20px; padding-left: 70px;\">Sign in</a>\r\n");
      out.write("					");
 } else { 
      out.write("\r\n");
      out.write("						<a href=\"/user/logOut.do\" style=\" font-family: 'Nanum Pen Script', cursive; font-size: 24px; padding-left: 40px;\">");
      out.print(id );
      out.write(" 님 Log out</a>\r\n");
      out.write("					");
} 
      out.write("\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		<hr style=\" width: 90%; height: 1.5px; border: none; background-color: #666666;\"/>\r\n");
      out.write("				<ul class=\"nav2\">\r\n");
      out.write("					<li class=\"colorlib-active\"><a href=\"/spoilbroth/mystudy.do\">Home</a></li>\r\n");
      out.write("					<li class=\"nana0\"><a href=\"/face/faceregister.do\">Face Register</a></li>\r\n");
      out.write("					<li class=\"nana1\"><a href=\"/mbti/mbtimain.do\">MBTI Analysis</a></li>\r\n");
      out.write("					<li class=\"nana2\"><a href=\"/study/match.do\">Study Matching</a></li>\r\n");
      out.write("					<li class=\"nana3\"><a href=\"/study/contest.do\">Study Imformation</a></li>\r\n");
      out.write("					<li class=\"nana4\"><a href=\"/study/studyplace.do\">Study Place</a></li>\r\n");
      out.write("					<li class=\"nana5\"><a href=\"/mypage/setting.do\">Setting</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</nav>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"colorlib-footer\" style=\"padding-bottom: 20px;\">\r\n");
      out.write("				<h1 id=\"colorlib-logo\" class=\"mb-4\">\r\n");
      out.write("					<a href=\"/spoilbroth/main.do\" style=\"background-image: url(/andrea-master/images/bg_1.jpg); font-size: 57px;\">Spoilbroth</a>\r\n");
      out.write("				</h1>\r\n");
      out.write("				<span style=\"font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; font-size: 28px;\">요리사가 너무 많으면 수프를 망친다.</span>\r\n");
      out.write("				<div class=\"mb-4\">\r\n");
      out.write("					<h3>Subscribe for Spoilbroth</h3>\r\n");
      out.write("					<form action=\"#\" class=\"colorlib-subscribe-form\">\r\n");
      out.write("						<div class=\"form-group d-flex\">\r\n");
      out.write("							<div class=\"icon\">\r\n");
      out.write("								<span class=\"icon-paper-plane\"></span>\r\n");
      out.write("							</div>\r\n");
      out.write("							<input type=\"text\" class=\"form-control\"\r\n");
      out.write("								placeholder=\"Enter Email Address\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("		</aside>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"/andrea-master/js/jquery.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("    var url = window.location.pathname;  \r\n");
      out.write("    var activePage = url.substring(url.lastIndexOf('/')+1);\r\n");
      out.write("    console.log(\"activePage: \" + activePage);\r\n");
      out.write("    \r\n");
      out.write("    $('.nav2 li a').each(function(){  \r\n");
      out.write("        var currentPage = this.href.substring(this.href.lastIndexOf('/')+1);\r\n");
      out.write("		console.log(\"currentPage : \"+currentPage)\r\n");
      out.write("		\r\n");
      out.write("        if (activePage == currentPage) {\r\n");
      out.write("        	$(\".nav2\").find(\".colorlib-active\").removeClass(\"colorlib-active\");\r\n");
      out.write("            $(this).parent().addClass('colorlib-active');\r\n");
      out.write("            $(this).addClass('colorlib-active');\r\n");
      out.write("            \r\n");
      out.write("        }else if(activePage == \"faceregister.do\"){\r\n");
      out.write("        	$(\".nav2\").find(\".colorlib-active\").removeClass(\"colorlib-active\");\r\n");
      out.write("        	$('.nana0').addClass('colorlib-active');\r\n");
      out.write("        }else if(activePage == \"mbtianalysis.do\"){\r\n");
      out.write("        	$(\".nav2\").find(\".colorlib-active\").removeClass(\"colorlib-active\");\r\n");
      out.write("        	$('.nana1').addClass('colorlib-active');\r\n");
      out.write("        }else if(activePage == \"match.do\"){\r\n");
      out.write("        	$(\".nav2\").find(\".colorlib-active\").removeClass(\"colorlib-active\");\r\n");
      out.write("        	$('.nana2').addClass('colorlib-active');\r\n");
      out.write("        }else if(activePage == \"contest.do\"){\r\n");
      out.write("        	$(\".nav2\").find(\".colorlib-active\").removeClass(\"colorlib-active\");\r\n");
      out.write("        	$('.nana3').addClass('colorlib-active');\r\n");
      out.write("        }else if(activePage == \"studyplace.do\"){\r\n");
      out.write("        	$(\".nav2\").find(\".colorlib-active\").removeClass(\"colorlib-active\");\r\n");
      out.write("        	$('.nana4').addClass('colorlib-active');\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("		<!-- END 왼쪽 NANI -->\r\n");
      out.write("\r\n");
      out.write("		<!-- START 상단 NANI -->\r\n");
      out.write("		<div class=\"padding\" style=\"padding-bottom: 55px;\"></div>\r\n");
      out.write("		<div class=\"sidebar-heading\"\r\n");
      out.write("			style=\"text-align: center; position: fixed; top: 0; width: 100%; height: 70px; background-color: #fff; z-index: 5; padding-top: 20px; font-weight: 500; color: black;\">\r\n");
      out.write("			<div class=\"hh\" style=\"font-size: 23px; height: 32px;\">\r\n");
      out.write("				<span>S</span><span>T</span><span>U</span><span>D</span><span>Y</span><span>&nbsp;</span><span>M</span><span>A</span><span>T</span><span>C</span><span>H</span><span>I</span><span>N</span><span>G</span>\r\n");
      out.write("			</div>\r\n");
      out.write("			<hr\r\n");
      out.write("				style=\"width: 90%; height: 1.5px; border: none; background-color: #666666;\">\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- END 상단 NANI -->\r\n");
      out.write("\r\n");
      out.write("		<!-- 메인 페이지 START-->\r\n");
      out.write("		<div id=\"colorlib-main\">\r\n");
      out.write("			<section class=\"ftco-section ftco-no-pt ftco-no-pb\">\r\n");
      out.write("				<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("					<!-- 왼쪽 오른쪽 2분할 -->\r\n");
      out.write("					<div class=\"row d-flex\">\r\n");
      out.write("\r\n");
      out.write("						<!-- 왼쪽 스크립트 -->\r\n");
      out.write("						<div class=\"col-xl-8 px-md-5\" style=\"background-color: #f7fbff;\">\r\n");
      out.write("							<!-- 스터디 개설  START -->\r\n");
      out.write("							<div class=\"\" style=\"margin-left: 20px\">\r\n");
      out.write("								<label\r\n");
      out.write("									style=\"font-size: 30px; font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; margin-top: 18px; margin-bottom: -8px;\">\r\n");
      out.write("									");
      out.print(study_name);
      out.write(" 팀의 커뮤니티\r\n");
      out.write("								</label>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"emp-profile\">\r\n");
      out.write("								<!-- 사진 프로필 START -->\r\n");
      out.write("								<div class=\"d-flex card p-3\" style=\"magin: -11px;\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("									<form id=\"uploadForm\" enctype=\"multipart/form-data\">\r\n");
      out.write("										<div class=\"d-flex align-items-center\">\r\n");
      out.write("											<div class=\"image\">\r\n");
      out.write("												<img id=\"preview-image\" src=\"");
      out.print(study_img);
      out.write("\" class=\"rounded\"\r\n");
      out.write("													width=\"100%\">\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div id=\"input-image\"\r\n");
      out.write("											class=\"button mt-2 d-flex flex-row align-items-center\">\r\n");
      out.write("											<input type=\"file\" id=\"file\" name=\"fileUplod2\"\r\n");
      out.write("												onchange=\"changeValue(this)\" style=\"display: none\" /> <input\r\n");
      out.write("												type=\"hidden\" name=\"study_name\" value=\"");
      out.print(study_name);
      out.write("\">\r\n");
      out.write("											<button class=\"btn btn-sm btn-primary w-100\" id=\"btn-upload\"\r\n");
      out.write("												style=\"margin-right: 2px;\">Select File</button>\r\n");
      out.write("											<button id=\"btnUpload\" class=\"btn btn-sm btn-primary w-100\"\r\n");
      out.write("												style=\"margin-left: 2px;\">Register</button>\r\n");
      out.write("										</div>\r\n");
      out.write("									</form>\r\n");
      out.write("\r\n");
      out.write("									<!-- 스터디 정보 -->\r\n");
      out.write("									<hr>\r\n");
      out.write("									<div class=\"form-group\" style=\"margin-bottom: 0px;\">\r\n");
      out.write("										<label\r\n");
      out.write("											style=\"font-size: 22px; font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; margin-bottom: 0px;\">\r\n");
      out.write("											Title : ");
      out.print(study_title);
      out.write("\r\n");
      out.write("										</label><br> <label\r\n");
      out.write("											style=\"font-size: 22px; font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; margin-bottom: 0px;\">\r\n");
      out.write("											스터디 시작일 : ");
      out.print(sDTO.getStudy_dt());
      out.write("\r\n");
      out.write("										</label><br> <label\r\n");
      out.write("											style=\"font-size: 22px; font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; margin-bottom: 0px;\">\r\n");
      out.write("											멤버 : ");
      out.print(sDTO.getStudy_member());
      out.write("\r\n");
      out.write("										</label><br> <label\r\n");
      out.write("											style=\"font-size: 22px; font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; margin-bottom: 0px;\">\r\n");
      out.write("											멤버의 MBTI : ");
      out.print(member_mbti);
      out.write("\r\n");
      out.write("										</label><br>\r\n");
      out.write("										<div class=\"profile-card\"\r\n");
      out.write("											style=\"padding-right: 3px; padding-left: 3px;\">\r\n");
      out.write("											");

												for (int k = 0; k < mbti_score; k++) {
											
      out.write("\r\n");
      out.write("											<svg version=\"1.1\" id=\"Capa_1\"\r\n");
      out.write("												xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("												xmlns:xlink=\"http://www.w3.org/1999/xlink\" x=\"0px\" y=\"0px\"\r\n");
      out.write("												width=\"22\" height=\"22\" viewBox=\"0 0 422.448 422.448\"\r\n");
      out.write("												style=\"enable-background: new 0 0 422.448 422.448;\"\r\n");
      out.write("												xml:space=\"preserve\">\r\n");
      out.write("										<path style=\"fill:#FF4979;\"\r\n");
      out.write("													d=\"M387.15,59.153c-47.066-47.065-123.374-47.065-170.44,0l-4,4l-4-4\r\n");
      out.write("											C163.342,10.448,87.081,7.742,38.376,53.109s-51.412,121.628-6.044,170.334c1.885,2.023,3.839,3.981,5.858,5.871l170.8,170.8\r\n");
      out.write("											c2.018,1.981,5.217,2.085,7.36,0.24l170.8-170.8c47.065-47.066,47.065-123.374,0-170.44L387.15,59.153z\" />\r\n");
      out.write("										</svg>\r\n");
      out.write("											");

												}
											
      out.write("\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"form-group mt-3\">\r\n");
      out.write("										<label\r\n");
      out.write("											style=\"font-size: 25px; font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; margin-bottom: 0px;\">\r\n");
      out.write("											알림</label>\r\n");
      out.write("										<div class=\"card fontstyle p-2\"\r\n");
      out.write("											style=\"font-size: 22px; font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; margin-bottom: 0px;\">\r\n");
      out.write("											<div id=\"text_aera\">");
      out.print(sDTO.getStudy_notify());
      out.write("</div>\r\n");
      out.write("											<!-- 스터디 개설자만 알림을 수정할 수 있음 -->\r\n");
      out.write("											");

												if (sDTO.getStudy_creator().equals(uDTO.getUser_id())) {
											
      out.write("\r\n");
      out.write("											<button class=\"btn btn-sm btn-primary w-100\" id=\"btn-upload\"\r\n");
      out.write("												style=\"margin-right: 2px;\" data-toggle=\"modal\"\r\n");
      out.write("												data-target=\"#exampleModalCenter\">알림 수정하기</button>\r\n");
      out.write("											");

												} else {
											}
											
      out.write("\r\n");
      out.write("										</div>\r\n");
      out.write("										<!-- modal 알림창  -->\r\n");
      out.write("										<!-- Modal -->\r\n");
      out.write("										<div class=\"modal fade\" id=\"exampleModalCenter\" tabindex=\"-1\"\r\n");
      out.write("											role=\"dialog\" aria-labelledby=\"exampleModalCenterTitle\"\r\n");
      out.write("											aria-hidden=\"true\"\r\n");
      out.write("											style=\"font-size: 22px; font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; margin-bottom: 0px;\">\r\n");
      out.write("											<div class=\"modal-dialog modal-dialog-centered\"\r\n");
      out.write("												role=\"document\">\r\n");
      out.write("												<div class=\"modal-content\">\r\n");
      out.write("													<div class=\"modal-header\">\r\n");
      out.write("														<h5 class=\"modal-title\" style=\"font-size: 30px;\"\r\n");
      out.write("															id=\"exampleModalLongTitle\">알림 수정하기</h5>\r\n");
      out.write("														<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("															aria-label=\"Close\">\r\n");
      out.write("															<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("														</button>\r\n");
      out.write("													</div>\r\n");
      out.write("													<div class=\"modal-body\">\r\n");
      out.write("														<textarea cols=\"50\" rows=\"10\" style=\"width: 100%\"\r\n");
      out.write("															id=\"text_modify\">");
      out.print(sDTO.getStudy_notify());
      out.write("</textarea>\r\n");
      out.write("													</div>\r\n");
      out.write("													<div class=\"modal-footer\" style=\"font-size: 25px;\">\r\n");
      out.write("														<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("															data-dismiss=\"modal\">닫기</button>\r\n");
      out.write("														<button type=\"button\" class=\"btn btn-primary\"\r\n");
      out.write("															onclick=\"text_modify();\">수정하기</button>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<!-- model 끝 -->\r\n");
      out.write("\r\n");
      out.write("									</div>\r\n");
      out.write("									<!-- 멀티 게시판  -->\r\n");
      out.write("									<div style=\"display: flex\">\r\n");
      out.write("										<div style=\"margin: 0 auto;\">\r\n");
      out.write("											<label\r\n");
      out.write("												style=\"font-size: 30px; font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; margin-bottom: 0px;\">\r\n");
      out.write("												게시판</label>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div>\r\n");
      out.write("											<button type=\"button\" class=\"btn btn-outline-warning\"\r\n");
      out.write("												onclick=\"location.href='/chat/chatting.do?study_name=거북목'\"\r\n");
      out.write("												style=\"font-weight: 600; color: tomato; border-width: revert; border-color: tomato;\">\r\n");
      out.write("												Let's 채팅</button>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<hr>\r\n");
      out.write("									<!-- 게시판 -->\r\n");
      out.write("									<table id=\"example\" class=\"display\"\r\n");
      out.write("										style=\"width: 100%; font-size: 20px; font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; margin-bottom: 0px;\">\r\n");
      out.write("										<thead style=\"font-size: 15px\";>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<th>no</th>\r\n");
      out.write("												<th>title</th>\r\n");
      out.write("												<th>name</th>\r\n");
      out.write("												<th>v</th>\r\n");
      out.write("\r\n");
      out.write("											</tr>\r\n");
      out.write("										</thead>\r\n");
      out.write("										");

											for (int i = 0; i < rList.size(); i++) {
											BoardDTO rDTO = rList.get(i);
											if (rDTO == null) {
												rDTO = new BoardDTO();
											}
										
      out.write("\r\n");
      out.write("										<tr>\r\n");
      out.write("											<td style=\"font-size: 15px\";>\r\n");
      out.write("												");

													// 공지글이라면, [공지]표시
												if (CmmUtil.nvl(rDTO.getNotice_yn()).equals("1")) {
													out.print("<b>[공지]</b>");
												} else {
													out.print(CmmUtil.nvl(rDTO.getNotice_seq()));
												}
												
      out.write("\r\n");
      out.write("											</td>\r\n");
      out.write("											<td><a style=\"color: brown;\"\r\n");
      out.write("												href=\"javascript:doDetail('");
      out.print(CmmUtil.nvl(rDTO.getNotice_seq()));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(CmmUtil.nvl(study_seq));
      out.write("');\">\r\n");
      out.write("													");
      out.print(CmmUtil.nvl(rDTO.getTitle()));
      out.write("</a></td>\r\n");
      out.write("											<th style=\"font-size: 15px\";>");
      out.print(CmmUtil.nvl(rDTO.getUser_name()));
      out.write("\r\n");
      out.write("											</th>\r\n");
      out.write("											<th style=\"font-size: 15px\";>");
      out.print(CmmUtil.nvl(rDTO.getRead_cnt()));
      out.write("\r\n");
      out.write("											</th>\r\n");
      out.write("										</tr>\r\n");
      out.write("										");

											}
										
      out.write("\r\n");
      out.write("									</table>\r\n");
      out.write("									<div\r\n");
      out.write("										style=\"font-size: 20px; font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; margin-bottom: 0px;\">\r\n");
      out.write("										<a href=\"javascript:newReg('");
      out.print(study_seq);
      out.write("');\"> [글쓰기]</a>\r\n");
      out.write("									</div>\r\n");
      out.write("									<!-- 스터디 개설  END -->\r\n");
      out.write("									");

										if (user_id.equals(study_creator)) {
									
      out.write("\r\n");
      out.write("									<button id=\"btnUpload\" class=\"btn btn-sm btn-danger w-100\"\r\n");
      out.write("										style=\"margin-top: 20px; margin-left: 2px;\" onclick=\"del();\">스터디\r\n");
      out.write("										삭제하기</button>\r\n");
      out.write("\r\n");
      out.write("									");

										} else {
									
      out.write("\r\n");
      out.write("\r\n");
      out.write("									<button id=\"btnUpload\" class=\"btn btn-sm btn-danger w-100\"\r\n");
      out.write("										style=\"margin-top: 20px; margin-left: 2px;\" onclick=\"leave();\">스터디\r\n");
      out.write("										탈퇴하기</button>\r\n");
      out.write("\r\n");
      out.write("									");

										}
									
      out.write("\r\n");
      out.write("\r\n");
      out.write("									<hr style=\"margin-top: 10px; margin-bottom: 0px;\" />\r\n");
      out.write("\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- 왼쪽 스크립트 끝 -->\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</section>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- 메인 페이지 END-->\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- 전체 페이지 END-->\r\n");
      out.write("\r\n");
      out.write("	<!-- loader -->\r\n");
      out.write("	<div id=\"ftco-loader\" class=\"fullscreen\">\r\n");
      out.write("		<svg class=\"circular\" width=\"48px\" height=\"48px\">\r\n");
      out.write("			<circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\"\r\n");
      out.write("				troke-width=\"4\" stroke=\"#eeeeee\"></circle>\r\n");
      out.write("			<circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\"\r\n");
      out.write("				stroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#F96D00\"></circle></svg>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<script src=\"/andrea-master/js/jquery.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/popper.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/bootstrap.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/jquery.stellar.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/owl.carousel.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/aos.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/jquery.animateNumber.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/scrollax.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/main.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("//상세보기 이동\r\n");
      out.write("function doDetail(seq, seq2){\r\n");
      out.write("	location.href=\"/board/BoardInfo.do?notice_seq=\"+seq+\"&study_seq=\"+seq2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function newReg(seq){\r\n");
      out.write("	location.href=\"/board/BoardReg.do?study_seq=\"+seq;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("		$(function () {\r\n");
      out.write("			$('#btn-upload').click(function (e) {\r\n");
      out.write("				e.preventDefault();\r\n");
      out.write("				$('#file').click();\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		function readImage(input) {\r\n");
      out.write("		    // 인풋 태그에 파일이 있는 경우\r\n");
      out.write("		    if(input.files && input.files[0]) {\r\n");
      out.write("		       \r\n");
      out.write("		        // FileReader 인스턴스 생성\r\n");
      out.write("		        const reader = new FileReader()\r\n");
      out.write("		        // 이미지가 로드가 된 경우\r\n");
      out.write("		        reader.onload = e => {\r\n");
      out.write("		            const previewImage = document.getElementById(\"preview-image\")\r\n");
      out.write("		            console.log(\"previewImage : \" + previewImage)\r\n");
      out.write("		            previewImage.src = e.target.result\r\n");
      out.write("		        }\r\n");
      out.write("		        // reader가 이미지 읽도록 하기\r\n");
      out.write("		        reader.readAsDataURL(input.files[0])\r\n");
      out.write("		    }\r\n");
      out.write("		}\r\n");
      out.write("		// input file에 change 이벤트 부여\r\n");
      out.write("		const inputImage = document.getElementById(\"input-image\")\r\n");
      out.write("		inputImage.addEventListener(\"change\", e => {\r\n");
      out.write("		    readImage(e.target)\r\n");
      out.write("		})\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	$('#btnUpload').on('click', function(event) {\r\n");
      out.write("	    event.preventDefault();\r\n");
      out.write("	    \r\n");
      out.write("	    var form = $('#uploadForm')[0]\r\n");
      out.write("	    var data = new FormData(form);\r\n");
      out.write("	    $('#btnUpload').prop('disabled', true);\r\n");
      out.write("		\r\n");
      out.write("	    $.ajax({\r\n");
      out.write("	        type: \"POST\",\r\n");
      out.write("	        enctype: 'multipart/form-data',\r\n");
      out.write("	        url: \"/FileUplod2.do\",\r\n");
      out.write("	        data: data,\r\n");
      out.write("	        processData: false,\r\n");
      out.write("	        contentType: false,\r\n");
      out.write("	        cache: false,\r\n");
      out.write("	        timeout: 600000,\r\n");
      out.write("	        success: function (data) {\r\n");
      out.write("	        	$('#btnUpload').prop('disabled', false);\r\n");
      out.write("	        	alert('등록이 성공하였습니다.')\r\n");
      out.write("	        },\r\n");
      out.write("	        error: function (e) {\r\n");
      out.write("	            $('#btnUpload').prop('disabled', false);\r\n");
      out.write("	            alert('등록이 실패하였습니다.');\r\n");
      out.write("	        }\r\n");
      out.write("	    });\r\n");
      out.write("	})\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	$(document).ready(function() {\r\n");
      out.write("		$('#example').DataTable({\r\n");
      out.write("			\"columns\" : [\r\n");
      out.write("					{\"width\" : \"10%\"},\r\n");
      out.write("					{ \"width\" : \"80%\" },\r\n");
      out.write("					{ \"width\" : \"5%\" },\r\n");
      out.write("					{ \"width\" : \"5%\" } \r\n");
      out.write("			]\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("function del() {\r\n");
      out.write("	if (window.confirm('스터디 그룹을 삭제하시겠습니까?')){\r\n");
      out.write("		window.location = '/study/del.do?study_name=");
      out.print(study_name);
      out.write("';\r\n");
      out.write("	}else{\r\n");
      out.write("	    // They clicked no\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function leave() {\r\n");
      out.write("	if (window.confirm('스터디 그룹을 탈퇴하시겠습니까?')){\r\n");
      out.write("		window.location = '/study/leave.do?study_name=");
      out.print(study_name);
      out.write("';\r\n");
      out.write("	}else{\r\n");
      out.write("	    // They clicked no\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function text_modify() {\r\n");
      out.write("    let study_seq = ");
      out.print(sDTO.getStudy_seq());
      out.write("\r\n");
      out.write("    const study_notify = document.getElementById(\"text_modify\").value;\r\n");
      out.write("    console.log(study_notify);\r\n");
      out.write("\r\n");
      out.write("	let request = {\r\n");
      out.write("            method: 'POST',\r\n");
      out.write("            body: JSON.stringify({ study_seq : study_seq , study_notify : study_notify }),\r\n");
      out.write("            headers: {\r\n");
      out.write("                'Content-Type': 'application/json'\r\n");
      out.write("            }\r\n");
      out.write("        };\r\n");
      out.write("    \r\n");
      out.write("   fetch(\"/study/textModify.do\", request)\r\n");
      out.write("	.then(function(res){\r\n");
      out.write("		return res.text()\r\n");
      out.write("	})\r\n");
      out.write("	.then(function(data){\r\n");
      out.write("		console.log(data);\r\n");
      out.write("		if(data == 1){\r\n");
      out.write("		\r\n");
      out.write("		swal(\"수정이 완료 되었습니다.!\")\r\n");
      out.write("		.then((value) => {\r\n");
      out.write("			location.reload();\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		}else{\r\n");
      out.write("		swal(\"수정이 실패 되었습니다.!\")\r\n");
      out.write("		.then((value) => {\r\n");
      out.write("			location.reload();\r\n");
      out.write("		});\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("	})\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
