/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.71
 * Generated at: 2021-11-25 11:55:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.chat;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import poly.util.CmmUtil;
import static poly.util.CmmUtil.nvl;

public final class chatting_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/view/sidebar.jsp", Long.valueOf(1636443453083L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("static poly.util.CmmUtil.nvl");
    _jspx_imports_classes.add("poly.util.CmmUtil");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String study_name = (String)request.getAttribute("study_name");
	String study_seq = (String)request.getAttribute("study_seq");
	String user_id = (String) session.getAttribute("user_id");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Chatting</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Abril+Fatface&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"/andrea-master/css/open-iconic-bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/animate.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"/andrea-master/css/owl.theme.default.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/magnific-popup.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/aos.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/ionicons.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"/andrea-master/css/bootstrap-datepicker.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/jquery.timepicker.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/flaticon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/icomoon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/andrea-master/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- profile -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/profile.css\">\r\n");
      out.write("<link href=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css\" rel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("<script src=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- profile -->\r\n");
      out.write("\r\n");
      out.write("<!-- chatting -->\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	.chat_window {\r\n");
      out.write("	  \r\n");
      out.write("	  width: 100%;\r\n");
      out.write("	  max-width: 800px;\r\n");
      out.write("	  height: 600px;\r\n");
      out.write("	  border-radius: 10px;\r\n");
      out.write("	  background-color: #fff;\r\n");
      out.write("	  \r\n");
      out.write("	  box-shadow: 0 10px 20px rgba(0, 0, 0, 0.15);\r\n");
      out.write("	  background-color: #f8f8f8;\r\n");
      out.write("	  overflow: hidden;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.top_menu {\r\n");
      out.write("	  background-color: #fff;\r\n");
      out.write("	  width: 100%;\r\n");
      out.write("	  padding: 20px 0 15px;\r\n");
      out.write("	  box-shadow: 0 1px 30px rgba(0, 0, 0, 0.1);\r\n");
      out.write("	}\r\n");
      out.write("	.top_menu .buttons {\r\n");
      out.write("	  margin: 3px 0 0 20px;\r\n");
      out.write("	  position: absolute;\r\n");
      out.write("	}\r\n");
      out.write("	.top_menu .buttons .button {\r\n");
      out.write("	  width: 16px;\r\n");
      out.write("	  height: 16px;\r\n");
      out.write("	  border-radius: 50%;\r\n");
      out.write("	  display: inline-block;\r\n");
      out.write("	  margin-right: 10px;\r\n");
      out.write("	  position: relative;\r\n");
      out.write("	}\r\n");
      out.write("	.top_menu .buttons .button.close {\r\n");
      out.write("	  background-color: #f5886e;\r\n");
      out.write("	}\r\n");
      out.write("	.top_menu .buttons .button.minimize {\r\n");
      out.write("	  background-color: #fdbf68;\r\n");
      out.write("	}\r\n");
      out.write("	.top_menu .buttons .button.maximize {\r\n");
      out.write("	  background-color: #a3d063;\r\n");
      out.write("	}\r\n");
      out.write("	.top_menu .title {\r\n");
      out.write("	  text-align: center;\r\n");
      out.write("	  color: #bcbdc0;\r\n");
      out.write("	  font-size: 20px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.messages {\r\n");
      out.write("	  position: relative;\r\n");
      out.write("	  list-style: none;\r\n");
      out.write("	  padding: 20px 10px 0 10px;\r\n");
      out.write("	  margin: 0;\r\n");
      out.write("	  height: 440px;\r\n");
      out.write("	  overflow: scroll;\r\n");
      out.write("	}\r\n");
      out.write("	.messages .message {\r\n");
      out.write("	  clear: both;\r\n");
      out.write("	  overflow: hidden;\r\n");
      out.write("	  margin-bottom: 20px;\r\n");
      out.write("	  transition: all 0.5s linear;\r\n");
      out.write("	  opacity: 0;\r\n");
      out.write("	}\r\n");
      out.write("	.messages .message.left .avatar {\r\n");
      out.write("	  background-color: #f5886e;\r\n");
      out.write("	  float: left;\r\n");
      out.write("	}\r\n");
      out.write("	.messages .message.left .text_wrapper {\r\n");
      out.write("	  background-color: #ffe6cb;\r\n");
      out.write("	  margin-left: 20px;\r\n");
      out.write("	}\r\n");
      out.write("	.messages .message.left .text_wrapper::after, .messages .message.left .text_wrapper::before {\r\n");
      out.write("	  right: 100%;\r\n");
      out.write("	  border-right-color: #ffe6cb;\r\n");
      out.write("	}\r\n");
      out.write("	.messages .message.left .text {\r\n");
      out.write("	  color: #c48843;\r\n");
      out.write("	}\r\n");
      out.write("	.messages .message.right .avatar {\r\n");
      out.write("	  background-color: #fdbf68;\r\n");
      out.write("	  float: right;\r\n");
      out.write("	}\r\n");
      out.write("	.messages .message.right .text_wrapper {\r\n");
      out.write("	  background-color: #c7eafc;\r\n");
      out.write("	  margin-right: 20px;\r\n");
      out.write("	  float: right;\r\n");
      out.write("	}\r\n");
      out.write("	.messages .message.right .text_wrapper::after, .messages .message.right .text_wrapper::before {\r\n");
      out.write("	  left: 100%;\r\n");
      out.write("	  border-left-color: #c7eafc;\r\n");
      out.write("	}\r\n");
      out.write("	.messages .message.right .text {\r\n");
      out.write("	  color: #45829b;\r\n");
      out.write("	}\r\n");
      out.write("	.messages .message.appeared {\r\n");
      out.write("	  opacity: 1;\r\n");
      out.write("	}\r\n");
      out.write("	.messages .message .avatar {\r\n");
      out.write("	  width: 60px;\r\n");
      out.write("	  height: 60px;\r\n");
      out.write("	  border-radius: 50%;\r\n");
      out.write("	  display: inline-block;\r\n");
      out.write("	}\r\n");
      out.write("	.messages .message .text_wrapper {\r\n");
      out.write("	  display: inline-block;\r\n");
      out.write("	  padding: 20px;\r\n");
      out.write("	  border-radius: 6px;\r\n");
      out.write("	  width: calc(100% - 85px);\r\n");
      out.write("	  min-width: 100px;\r\n");
      out.write("	  position: relative;\r\n");
      out.write("	}\r\n");
      out.write("	.messages .message .text_wrapper::after, .messages .message .text_wrapper:before {\r\n");
      out.write("	  top: 18px;\r\n");
      out.write("	  border: solid transparent;\r\n");
      out.write("	  content: \" \";\r\n");
      out.write("	  height: 0;\r\n");
      out.write("	  width: 0;\r\n");
      out.write("	  position: absolute;\r\n");
      out.write("	  pointer-events: none;\r\n");
      out.write("	}\r\n");
      out.write("	.messages .message .text_wrapper::after {\r\n");
      out.write("	  border-width: 13px;\r\n");
      out.write("	  margin-top: 0px;\r\n");
      out.write("	}\r\n");
      out.write("	.messages .message .text_wrapper::before {\r\n");
      out.write("	  border-width: 15px;\r\n");
      out.write("	  margin-top: -2px;\r\n");
      out.write("	}\r\n");
      out.write("	.messages .message .text_wrapper .text {\r\n");
      out.write("	  font-size: 18px;\r\n");
      out.write("	  font-weight: 300;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.bottom_wrapper {\r\n");
      out.write("	  position: relative;\r\n");
      out.write("	  width: 100%;\r\n");
      out.write("	  background-color: #fff;\r\n");
      out.write("	  padding: 20px 20px;\r\n");
      out.write("	  bottom: 0;\r\n");
      out.write("	  padding-left: 5px;\r\n");
      out.write("	  padding-right: 5px;\r\n");
      out.write("	}\r\n");
      out.write("	.bottom_wrapper .message_input_wrapper {\r\n");
      out.write("	  display: inline-block;\r\n");
      out.write("	  height: 50px;\r\n");
      out.write("	  border-radius: 25px;\r\n");
      out.write("	  border: 1px solid #bcbdc0;\r\n");
      out.write("	  width: 75%;\r\n");
      out.write("	  position: relative;\r\n");
      out.write("	  padding: 0 20px;\r\n");
      out.write("	}\r\n");
      out.write("	.bottom_wrapper .message_input_wrapper .message_input {\r\n");
      out.write("	  border: none;\r\n");
      out.write("	  height: 100%;\r\n");
      out.write("	  box-sizing: border-box;\r\n");
      out.write("	  width: calc(100% - 40px);\r\n");
      out.write("	  position: absolute;\r\n");
      out.write("	  outline-width: 0;\r\n");
      out.write("	  color: gray;\r\n");
      out.write("	}\r\n");
      out.write("	.bottom_wrapper .send_message {\r\n");
      out.write("	  width: 24%;\r\n");
      out.write("	  height: 50px;\r\n");
      out.write("	  display: inline-block;\r\n");
      out.write("	  border-radius: 50px;\r\n");
      out.write("	  background-color: #a3d063;\r\n");
      out.write("	  border: 2px solid #a3d063;\r\n");
      out.write("	  color: #fff;\r\n");
      out.write("	  cursor: pointer;\r\n");
      out.write("	  transition: all 0.2s linear;\r\n");
      out.write("	  text-align: center;\r\n");
      out.write("	  float: right;\r\n");
      out.write("	}\r\n");
      out.write("	.bottom_wrapper .send_message:hover {\r\n");
      out.write("	  color: #a3d063;\r\n");
      out.write("	  background-color: #fff;\r\n");
      out.write("	}\r\n");
      out.write("	.bottom_wrapper .send_message .text {\r\n");
      out.write("	  font-size: 18px;\r\n");
      out.write("	  font-weight: 300;\r\n");
      out.write("	  display: inline-block;\r\n");
      out.write("	  line-height: 48px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.message_template {\r\n");
      out.write("	  display: none;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("<!-- chatting -->\r\n");
      out.write("</head>\r\n");
      out.write("<body data-aos-easing=\"slide\" data-aos-duration=\"800\" data-aos-delay=\"0\">\r\n");
      out.write("\r\n");
      out.write("	<!-- 전체 페이지 START-->\r\n");
      out.write("	<div id=\"colorlib-page\">\r\n");
      out.write("		<!-- START 왼쪽 NANI -->\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("\r\n");


	String id = nvl((String)session.getAttribute("user_id"));
	String date = nvl((String)session.getAttribute("join_dt")); 

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<!-- 구글폰트 -->\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Do+Hyeon&family=Nanum+Pen+Script&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<a href=\"#\" class=\"js-colorlib-nav-toggle colorlib-nav-toggle\"><i></i></a>\r\n");
      out.write("		<aside id=\"colorlib-aside\" role=\"complementary\" class=\"js-fullheight\"\r\n");
      out.write("			style=\"height: 812px;\">\r\n");
      out.write("			\r\n");
      out.write("			<nav id=\"colorlib-main-menu\" role=\"navigation\">\r\n");
      out.write("			<a href=\"single.html\" class=\"img img-2\" style=\"background-image: url(/andrea-master/images/image_1.jpg);\"></a>\r\n");
      out.write("			<div class=\"colorlib-active\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li>\r\n");
      out.write("					");
if(date.isEmpty()) { 
      out.write("\r\n");
      out.write("						<a href=\"/user/login.do\" style=\"font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; font-size: 32px;\">가입 하시겠습니까?</a>\r\n");
      out.write("					");
 } else { 
      out.write("\r\n");
      out.write("						<a href=\"#\" style=\"font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; font-size: 24px;\" method=post>첫방문  : ");
      out.print(date );
      out.write("</a>\r\n");
      out.write("					");
} 
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				</li>\r\n");
      out.write("				<li>\r\n");
      out.write("					");
if(id.isEmpty()) { 
      out.write("\r\n");
      out.write("						<a href=\"/user/login.do\" style= \"font-family: 'Nanum Pen Script', cursive; font-size: 20px; padding-left: 70px;\">Sign in</a>\r\n");
      out.write("					");
 } else { 
      out.write("\r\n");
      out.write("						<a href=\"/user/logOut.do\" style=\" font-family: 'Nanum Pen Script', cursive; font-size: 24px; padding-left: 40px;\">");
      out.print(id );
      out.write(" 님 Log out</a>\r\n");
      out.write("					");
} 
      out.write("\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		<hr style=\" width: 90%; height: 1.5px; border: none; background-color: #666666;\"/>\r\n");
      out.write("				<ul class=\"nav2\">\r\n");
      out.write("					<li class=\"colorlib-active\"><a href=\"/spoilbroth/mystudy.do\">Home</a></li>\r\n");
      out.write("					<li class=\"nana0\"><a href=\"/face/faceregister.do\">Face Register</a></li>\r\n");
      out.write("					<li class=\"nana1\"><a href=\"/mbti/mbtimain.do\">MBTI Analysis</a></li>\r\n");
      out.write("					<li class=\"nana2\"><a href=\"/study/match.do\">Study Matching</a></li>\r\n");
      out.write("					<li class=\"nana3\"><a href=\"/study/contest.do\">Study Imformation</a></li>\r\n");
      out.write("					<li class=\"nana4\"><a href=\"/study/studyplace.do\">Study Place</a></li>\r\n");
      out.write("					<li class=\"nana5\"><a href=\"/mypage/setting.do\">Setting</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</nav>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"colorlib-footer\" style=\"padding-bottom: 20px;\">\r\n");
      out.write("				<h1 id=\"colorlib-logo\" class=\"mb-4\">\r\n");
      out.write("					<a href=\"/spoilbroth/main.do\" style=\"background-image: url(/andrea-master/images/bg_1.jpg); font-size: 57px;\">Spoilbroth</a>\r\n");
      out.write("				</h1>\r\n");
      out.write("				<span style=\"font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; font-size: 28px;\">요리사가 너무 많으면 수프를 망친다.</span>\r\n");
      out.write("				<div class=\"mb-4\">\r\n");
      out.write("					<h3>Subscribe for Spoilbroth</h3>\r\n");
      out.write("					<form action=\"#\" class=\"colorlib-subscribe-form\">\r\n");
      out.write("						<div class=\"form-group d-flex\">\r\n");
      out.write("							<div class=\"icon\">\r\n");
      out.write("								<span class=\"icon-paper-plane\"></span>\r\n");
      out.write("							</div>\r\n");
      out.write("							<input type=\"text\" class=\"form-control\"\r\n");
      out.write("								placeholder=\"Enter Email Address\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("		</aside>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"/andrea-master/js/jquery.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("    var url = window.location.pathname;  \r\n");
      out.write("    var activePage = url.substring(url.lastIndexOf('/')+1);\r\n");
      out.write("    console.log(\"activePage: \" + activePage);\r\n");
      out.write("    \r\n");
      out.write("    $('.nav2 li a').each(function(){  \r\n");
      out.write("        var currentPage = this.href.substring(this.href.lastIndexOf('/')+1);\r\n");
      out.write("		console.log(\"currentPage : \"+currentPage)\r\n");
      out.write("		\r\n");
      out.write("        if (activePage == currentPage) {\r\n");
      out.write("        	$(\".nav2\").find(\".colorlib-active\").removeClass(\"colorlib-active\");\r\n");
      out.write("            $(this).parent().addClass('colorlib-active');\r\n");
      out.write("            $(this).addClass('colorlib-active');\r\n");
      out.write("            \r\n");
      out.write("        }else if(activePage == \"faceregister.do\"){\r\n");
      out.write("        	$(\".nav2\").find(\".colorlib-active\").removeClass(\"colorlib-active\");\r\n");
      out.write("        	$('.nana0').addClass('colorlib-active');\r\n");
      out.write("        }else if(activePage == \"mbtianalysis.do\"){\r\n");
      out.write("        	$(\".nav2\").find(\".colorlib-active\").removeClass(\"colorlib-active\");\r\n");
      out.write("        	$('.nana1').addClass('colorlib-active');\r\n");
      out.write("        }else if(activePage == \"match.do\"){\r\n");
      out.write("        	$(\".nav2\").find(\".colorlib-active\").removeClass(\"colorlib-active\");\r\n");
      out.write("        	$('.nana2').addClass('colorlib-active');\r\n");
      out.write("        }else if(activePage == \"contest.do\"){\r\n");
      out.write("        	$(\".nav2\").find(\".colorlib-active\").removeClass(\"colorlib-active\");\r\n");
      out.write("        	$('.nana3').addClass('colorlib-active');\r\n");
      out.write("        }else if(activePage == \"studyplace.do\"){\r\n");
      out.write("        	$(\".nav2\").find(\".colorlib-active\").removeClass(\"colorlib-active\");\r\n");
      out.write("        	$('.nana4').addClass('colorlib-active');\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("		<!-- END 왼쪽 NANI -->\r\n");
      out.write("\r\n");
      out.write("		<!-- START 상단 NANI -->\r\n");
      out.write("		<div class=\"padding\" style=\"padding-bottom: 55px;\"></div>\r\n");
      out.write("		<div class=\"sidebar-heading\"\r\n");
      out.write("			style=\"text-align: center; position: fixed; top: 0; width: 100%; height: 70px; background-color: #fff; z-index: 5; padding-top: 20px; font-weight: 500; color: black;\">\r\n");
      out.write("			<div class=\"hh\" style=\"font-size: 23px; height: 32px;\">\r\n");
      out.write("				<span>S</span><span>T</span><span>U</span><span>D</span><span>Y</span><span>&nbsp;</span><span>C</span><span>H</span><span>A</span><span>T</span><span>T</span><span>I</span><span>N</span><span>G</span>\r\n");
      out.write("			</div>\r\n");
      out.write("			<hr\r\n");
      out.write("				style=\"width: 90%; height: 1.5px; border: none; background-color: #666666;\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- END 상단 NANI -->\r\n");
      out.write("\r\n");
      out.write("		<!-- 메인 페이지 START-->\r\n");
      out.write("		<div id=\"colorlib-main\">\r\n");
      out.write("			<section class=\"ftco-section ftco-no-pt ftco-no-pb\">\r\n");
      out.write("				<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("					<!-- 왼쪽 오른쪽 2분할 -->\r\n");
      out.write("					<div class=\"row d-flex\">\r\n");
      out.write("\r\n");
      out.write("						<!-- 왼쪽 스크립트 -->\r\n");
      out.write("						<div class=\"col-xl-8 px-md-5\" style=\"background-color: #f7fbff;\">\r\n");
      out.write("							<!-- 스터디 개설  START -->\r\n");
      out.write("							<div class=\"\" style=\"margin-left: 20px\">\r\n");
      out.write("								<label\r\n");
      out.write("									style=\"font-size: 30px; font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; margin-top: 18px; margin-bottom: -8px;\">\r\n");
      out.write("									");
      out.print(study_name);
      out.write(" 팀의 채팅창\r\n");
      out.write("								</label>\r\n");
      out.write("								<label\r\n");
      out.write("									style=\"font-size: 20px; font-family: 'Do Hyeon', sans-serif; font-family: 'Nanum Pen Script', cursive; margin-top: 18px; margin-bottom: -8px; float:right;\">\r\n");
      out.write("									By ");
      out.print(user_id);
      out.write("\r\n");
      out.write("								</label>\r\n");
      out.write("							</div>\r\n");
      out.write("							<hr>\r\n");
      out.write("							<div class=\"\">\r\n");
      out.write("								<!-- <div class=\"d-flex card p-3\" style=\"magin: -11px;\"> -->\r\n");
      out.write("									");
      out.write("\r\n");
      out.write("									<div class=\"buttons\">\r\n");
      out.write("									<button class=\"btn btn-info\" type=\"button\" onclick=\"openSocket()\" style=\"font-size: 12px;\">대화방참여</button>\r\n");
      out.write("									<button class=\"btn btn-warning\" type=\"button\" onclick=\"closeSocket();\" style=\"font-size: 12px;\">대화방 나가기</button>\r\n");
      out.write("									<button class=\"btn btn-success\" type=\"button\" onclick=\"pre();\" style=\"font-size: 12px;\">이전 메시지 불러오기</button>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"chat_window\">\r\n");
      out.write("										<div class=\"top_menu\">\r\n");
      out.write("											<div class=\"buttons\">\r\n");
      out.write("												<div class=\"button close\"></div>\r\n");
      out.write("												<div class=\"button minimize\"></div>\r\n");
      out.write("												<div class=\"button maximize\"></div>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"title\">Chat</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<!-- 메시지 창 -->\r\n");
      out.write("										<div id =\"chat\"></div>\r\n");
      out.write("										<ul class=\"messages\"></ul>\r\n");
      out.write("										\r\n");
      out.write("										<div class=\"bottom_wrapper clearfix\">\r\n");
      out.write("											<div class=\"message_input_wrapper\">\r\n");
      out.write("												<input type=\"text\" id=\"sender\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"display: none;\">\r\n");
      out.write("												<input type=\"text\" class=\"message_input\" placeholder=\"Type your message here...\" />\r\n");
      out.write("											</div>\r\n");
      out.write("										<!-- Send 메시지 -->\r\n");
      out.write("											<div class=\"send_message\" onclick=\"send();\">\r\n");
      out.write("												<div class=\"icon\"></div>\r\n");
      out.write("												<div class=\"text\">Send</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"message_template\">\r\n");
      out.write("										<li class=\"message\"><div class=\"avatar\"></div>\r\n");
      out.write("											<div class=\"text_wrapper\">\r\n");
      out.write("												<div class=\"text\"></div>\r\n");
      out.write("											</div></li>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<hr style=\"margin-top: 10px; margin-bottom: 0px;\" />\r\n");
      out.write("									\r\n");
      out.write("									\r\n");
      out.write("								<!-- </div> -->\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- 왼쪽 스크립트 끝 -->\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</section>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- 메인 페이지 END-->\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- 전체 페이지 END-->\r\n");
      out.write("\r\n");
      out.write("	<!-- loader -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script src=\"/andrea-master/js/jquery.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/popper.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/bootstrap.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/jquery.stellar.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/owl.carousel.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/aos.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/jquery.animateNumber.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/scrollax.min.js\"></script>\r\n");
      out.write("	<script src=\"/andrea-master/js/main.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	function getDatetime() {\r\n");
      out.write("		let _date = new Date();\r\n");
      out.write("		let _hours = _date.getHours();\r\n");
      out.write("		let _min = _date.getMinutes();\r\n");
      out.write("		_hours = _hours < 10 ? '0' + _hours : _hours\r\n");
      out.write("		_min = _min < 10 ? '0' + _min : _min\r\n");
      out.write("		return _hours + ':' + _min;\r\n");
      out.write("	}\r\n");
      out.write("	/* ##### websocket js start ##### */\r\n");
      out.write("	let ws;\r\n");
      out.write("	function openSocket() {\r\n");
      out.write("		console.log(\"openSocket\");\r\n");
      out.write("		if (ws !== undefined && ws.readyState !== WebSocket.CLOSED) {\r\n");
      out.write("			console.log(\"WebSocket is already opened.\");\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		//웹소켓 객체 만드는 코드\r\n");
      out.write("		// ws = new WebSocket(\"ws://http://spoilbroth.toast.paas-ta.com//echo.do\");\r\n");
      out.write("		ws = new WebSocket(\"wss://spoilbroth.toast.paas-ta.com/echo.do\");\r\n");
      out.write("\r\n");
      out.write("		ws.onopen = function(event) {\r\n");
      out.write("			if (event.data === undefined)\r\n");
      out.write("				return;\r\n");
      out.write("\r\n");
      out.write("			writeResponse(event.data);\r\n");
      out.write("		};\r\n");
      out.write("\r\n");
      out.write("		ws.onmessage = function(event) {\r\n");
      out.write("			writeResponse(event.data);\r\n");
      out.write("		};\r\n");
      out.write("		ws.onclose = function(event) {\r\n");
      out.write("			writeResponse(\"연결이 해제되었습니다.\");\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	function send() {\r\n");
      out.write("		var text = $(\".message_input\").val() + \",\" + document.getElementById(\"sender\").value;\r\n");
      out.write("		console.log(\"text : \" +text)\r\n");
      out.write("		ws.send(text);\r\n");
      out.write("		text = \"\";\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		let chat_id = '");
      out.print(user_id );
      out.write("';\r\n");
      out.write("		let chat_dt = getDatetime();\r\n");
      out.write("		let study_seq = ");
      out.print(study_seq );
      out.write(";\r\n");
      out.write("		let study_name = '");
      out.print(study_name );
      out.write("';\r\n");
      out.write("		let chat_content = $(\".message_input\").val();\r\n");
      out.write("		\r\n");
      out.write("		console.log(\"chat_id : \" + chat_id)\r\n");
      out.write("		var param = {};\r\n");
      out.write("		\r\n");
      out.write("		param['chat_id'] = chat_id;\r\n");
      out.write("		param['chat_dt'] = chat_dt;\r\n");
      out.write("		param['study_seq'] = study_seq;\r\n");
      out.write("		param['study_name'] = study_name;\r\n");
      out.write("		param['chat_contents'] = chat_content;\r\n");
      out.write("		\r\n");
      out.write("		console.table(param);\r\n");
      out.write("		\r\n");
      out.write("		 $.ajax({\r\n");
      out.write("	         url: \"/chat/messageeForRedis.do\",\r\n");
      out.write("	         type: 'POST',\r\n");
      out.write("	         data: param, \r\n");
      out.write("	         success:function(result) {\r\n");
      out.write("	            console.log(result);\r\n");
      out.write("	         },\r\n");
      out.write("	         error:function(e) {\r\n");
      out.write("	            console.log(e);\r\n");
      out.write("	         }\r\n");
      out.write("	      })\r\n");
      out.write("		\r\n");
      out.write("		$('.message_input').val('');\r\n");
      out.write("	}\r\n");
      out.write("	function closeSocket() {\r\n");
      out.write("		ws.close();\r\n");
      out.write("	}\r\n");
      out.write("	function writeResponse(text) {\r\n");
      out.write("		console.log(\"text : \" + text);\r\n");
      out.write("		let _dateTime = getDatetime();\r\n");
      out.write("		/* console.log(json.res_msg);\r\n");
      out.write("		let resHTML = \"\";\r\n");
      out.write("		resHTML += '<li class=\"clearfix\">';\r\n");
      out.write("		resHTML += '<span class=\"chat-img\">';\r\n");
      out.write("		resHTML += '<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/andrea-master/images/ISFP.png\">';\r\n");
      out.write("		resHTML += '</span>';\r\n");
      out.write("		resHTML += '<div class=\"chat-body clearfix \" style=\"display:flex; margin-left:5px\";>';\r\n");
      out.write("		resHTML += '<span class=\"chat_time\">' + _dateTime\r\n");
      out.write("				+ '</span>&nbsp&nbsp&nbsp&nbsp';\r\n");
      out.write("		resHTML += '<p>' + text + '</p>';\r\n");
      out.write("		resHTML += '</div>';\r\n");
      out.write("		resHTML += '</li>'; */\r\n");
      out.write("		let res = \"\";\r\n");
      out.write("		var qqq = text.substring(1,2);\r\n");
      out.write("		console.log(\"qqq : \" + qqq);\r\n");
      out.write("		\r\n");
      out.write("		var user_id = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("		console.log(\"user_id : \" + user_id);\r\n");
      out.write("		if(qqq == \"나\"){\r\n");
      out.write("			res += '<li class=\"message left appeared\" id=\"chat_ul\">';\r\n");
      out.write("			res += '<div class=\"avatar\"></div>';\r\n");
      out.write("			res += '<div class=\"text_wrapper\">';\r\n");
      out.write("			res += '<div class=\"text\" style=\"font-size: 20px; font-family: \\'Do Hyeon\\', sans-serif; font-family: \\'Nanum Pen Script\\', cursive;  margin-bottom: -8px;\">'+ _dateTime + '&nbsp;&nbsp;' + text + '</div>';\r\n");
      out.write("			res += '</div>';\r\n");
      out.write("			res += '</li>';\r\n");
      out.write("		}else{\r\n");
      out.write("			res += '<li class=\"message right appeared\" id=\"chat_ul\">';\r\n");
      out.write("			res += '<div class=\"avatar\"></div>';\r\n");
      out.write("			res += '<div class=\"text_wrapper\">';\r\n");
      out.write("			res += '<div class=\"text\" style=\"font-size: 20px; font-family: \\'Do Hyeon\\', sans-serif; font-family: \\'Nanum Pen Script\\', cursive;  margin-bottom: -8px;\">'+ _dateTime + '&nbsp;&nbsp;' + text + '</div>';\r\n");
      out.write("			res += '</div>';\r\n");
      out.write("			res += '</li>';\r\n");
      out.write("		}\r\n");
      out.write("		$(\".messages\").append(res);\r\n");
      out.write("		$messages = $('.messages');\r\n");
      out.write("        return $messages.animate({ scrollTop: $messages.prop('scrollHeight') }, 300);\r\n");
      out.write("	}\r\n");
      out.write("	openSocket(); // websocket open\r\n");
      out.write("	window.onbeforeunload = function(e) {\r\n");
      out.write("		closeSocket() // 페이지 벗어나면 websocket close\r\n");
      out.write("	};\r\n");
      out.write("	/* ##### websocket js end ##### */\r\n");
      out.write("	function clearText() {\r\n");
      out.write("		console.log(messages.parentNode);\r\n");
      out.write("		messages.parentNode.removeChild(messages)\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function pre(){\r\n");
      out.write("		console.log(\"pre start!!\");\r\n");
      out.write("		$.ajax({\r\n");
      out.write("	         url: \"/chat/messageeFromRedis.do\",\r\n");
      out.write("	         type: 'GET',\r\n");
      out.write("	         data: {\r\n");
      out.write("	        	 study_name : '");
      out.print(study_name);
      out.write("'\r\n");
      out.write("	         },\r\n");
      out.write("	         dataType: \"text\",\r\n");
      out.write("	         success:function(data) {\r\n");
      out.write("	            console.table(data);\r\n");
      out.write("	            \r\n");
      out.write("	            var result = data\r\n");
      out.write("	            /* $('#chat').html(data); */\r\n");
      out.write("	            $(\".messages\").append(data);\r\n");
      out.write("	            \r\n");
      out.write("	            \r\n");
      out.write("	           ");
      out.write("\r\n");
      out.write("	        	\r\n");
      out.write("	        	 /* console.log(\"data : \"+ data);\r\n");
      out.write("	        	 console.log(\"data.get[0] : \"+ data[0][0]['chat_contents']); */\r\n");
      out.write("	         },\r\n");
      out.write("	         error:function(e) {\r\n");
      out.write("	            console.log(e);\r\n");
      out.write("	         }\r\n");
      out.write("	      })\r\n");
      out.write("	      \r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	/* (function () {\r\n");
      out.write("	    var Message;\r\n");
      out.write("	    Message = function (arg) {\r\n");
      out.write("	        this.text = arg.text, this.message_side = arg.message_side;\r\n");
      out.write("	        this.draw = function (_this) {\r\n");
      out.write("	            return function () {\r\n");
      out.write("	                var $message;\r\n");
      out.write("	                $message = $($('.message_template').clone().html());\r\n");
      out.write("	                $message.attr('id','chat__ul').addClass(_this.message_side).find('.text').html(_this.text);\r\n");
      out.write("	                $('.messages').append($message);\r\n");
      out.write("	                return setTimeout(function () {\r\n");
      out.write("	                    return $message.addClass('appeared');\r\n");
      out.write("	                }, 0);\r\n");
      out.write("	            };\r\n");
      out.write("	        }(this);\r\n");
      out.write("	        return this;\r\n");
      out.write("	    };\r\n");
      out.write("	    $(function () {\r\n");
      out.write("	        var getMessageText, message_side, sendMessage;\r\n");
      out.write("	        message_side = 'right';\r\n");
      out.write("	        getMessageText = function () {\r\n");
      out.write("	            var $message_input;\r\n");
      out.write("	            $message_input = $('.message_input');\r\n");
      out.write("	            return $message_input.val();\r\n");
      out.write("	        };\r\n");
      out.write("	        sendMessage = function (text) {\r\n");
      out.write("	            var $messages, message;\r\n");
      out.write("	            if (text.trim() === '') {\r\n");
      out.write("	                return;\r\n");
      out.write("	            }\r\n");
      out.write("	            $('.message_input').val('');\r\n");
      out.write("	            $messages = $('.messages');\r\n");
      out.write("	            message_side = message_side === 'left' ? 'right' : 'left';\r\n");
      out.write("	            message = new Message({\r\n");
      out.write("	                text: text,\r\n");
      out.write("	                message_side: message_side\r\n");
      out.write("	            });\r\n");
      out.write("	            message.draw();\r\n");
      out.write("	            return $messages.animate({ scrollTop: $messages.prop('scrollHeight') }, 300);\r\n");
      out.write("	        };\r\n");
      out.write("	        $('.send_message').click(function (e) {\r\n");
      out.write("	            return sendMessage(getMessageText());\r\n");
      out.write("	        });\r\n");
      out.write("	        $('.message_input').keyup(function (e) {\r\n");
      out.write("	            if (e.which === 13) {\r\n");
      out.write("	                return sendMessage(getMessageText());\r\n");
      out.write("	            }\r\n");
      out.write("	        });\r\n");
      out.write("	        sendMessage('Hello Philip! :)');\r\n");
      out.write("	        setTimeout(function () {\r\n");
      out.write("	            return sendMessage('Hi Sandy! How are you?');\r\n");
      out.write("	        }, 1000);\r\n");
      out.write("	        return setTimeout(function () {\r\n");
      out.write("	            return sendMessage('I\\'m fine, thank you!');\r\n");
      out.write("	        }, 2000);\r\n");
      out.write("	    });\r\n");
      out.write("	}.call(this)); */\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
